/* Abdulrahman S. Al-Batati — portfolio content manifest (bilingual EN/AR).
   Images resolve to img/{w480|w960|w1600}/<slug>.webp (tools/build_images.py). */

export const IMG = (slug, w = "w960") => `img/${w}/${slug}.webp`;

export const PROFILE = {
  name: "Abdulrahman S. Al-Batati",
  name_ar: "عبدالرحمن صالح البطاطي",
  role: "Robotics & Autonomous Intelligent Systems",
  role_ar: "الروبوتات والأنظمة الذكية المستقلة",
  blurb:
    "Senior Research Assistant at Prince Sultan University's Robotics & IoT Lab, heading to a PhD at KFUPM. " +
    "Six years turning mechanical design, UAV autonomy, and reinforcement learning into machines that work in the real world — " +
    "drones, ground robots, and the perception kits that keep them located when GPS goes dark.",
  blurb_ar:
    "باحث أول في معمل الروبوتات وإنترنت الأشياء بجامعة الأمير سلطان، ومتوجّه إلى الدكتوراه في جامعة الملك فهد للبترول والمعادن. " +
    "ستّ سنوات في تحويل التصميم الميكانيكي واستقلالية الطائرات المسيّرة والتعلّم المعزّز إلى آلاتٍ تعمل في الواقع — " +
    "طائرات مسيّرة، وروبوتات أرضية، وحساسات تُبقيها متموضِعة حين ينقطع نظام تحديد المواقع.",
  origin: "It started as a childhood dream of being an inventor — not an engineer. The machines just made it real.",
  origin_ar: "بدأ الأمر حلمًا في الطفولة بأن أكون مُخترعًا — لا مهندسًا. والآلات هي ما جعلت الحلم حقيقة.",
  location: "Riyadh → Khobar, Saudi Arabia",
  location_ar: "الرياض ← الخبر، المملكة العربية السعودية",
  email: "asmalbatati@hotmail.com",
  links: {
    github: "https://github.com/asmbatati",
    linkedin: "https://www.linkedin.com/in/asmbatati",
    scholar: "https://scholar.google.com/citations?hl=en&user=cxrJK64AAAAJ",
  },
  languages: ["Arabic — native", "English — professional", "Chinese — HSK2"],
  languages_ar: ["العربية — اللغة الأم", "الإنجليزية — احترافية", "الصينية — HSK2"],
};

export const STATS = [
  { n: "10", label: "papers published", label_ar: "بحثًا منشورًا" },
  { n: "2", label: "patents granted", label_ar: "براءتا تصميم" },
  { n: "6+", label: "years in robotics", label_ar: "سنوات في الروبوتات" },
  { n: "8", label: "robots designed & built", label_ar: "روبوتات صُمّمت وبُنيت" },
];

export const PROJECTS = [
  { id: "proj-vtol-build", cat: "aerial", title: "VTOL UAV Platform", title_ar: "منصة طائرة VTOL", kind: "Flagship build", kind_ar: "أبرز الأعمال", year: "2023",
    blurb: "A large hybrid VTOL fixed-wing — vertical take-off, fixed-wing cruise. Designed, fabricated, and flown in-house for long-endurance missions.",
    blurb_ar: "طائرة هجينة كبيرة عمودية الإقلاع وثابتة الجناح — إقلاع عمودي وطيران انسيابي. صُمّمت وصُنّعت وطُيّرت داخليًا لمهامٍ طويلة المدى." },
  { id: "proj-taer", cat: "aerial", title: "TAER", title_ar: "طائر", kind: "VTOL · CAD", kind_ar: "تصميم VTOL", year: "2023",
    blurb: "Long-endurance tilt-tail VTOL concept: folding quad-lift arms over an efficient fixed-wing cruise body. Full SolidWorks design.",
    blurb_ar: "تصميم VTOL طويل المدى بأذرع رفع قابلة للطي فوق جسم ثابت الجناح عالي الكفاءة. تصميم كامل على SolidWorks." },
  { id: "proj-roboeye", cat: "sensor", title: "RoboEye", title_ar: "عين الروبوت", kind: "VIO sensor kit · patent", kind_ar: "حساس تموضع · براءة", year: "2024",
    blurb: "A compact visual-inertial localization kit (stereo + IMU on Raspberry Pi / Jetson) that keeps robots located in GPS-denied spaces. Patented industrial design.",
    blurb_ar: "حساس تموضع بصري-قصوري مُدمج (كاميرتان + وحدة قياس قصوري على Raspberry Pi / Jetson) يُبقي الروبوت متموضِعًا في الأماكن المحرومة من GPS. تصميم صناعي مُسجّل." },
  { id: "proj-amir", cat: "ground", title: "AMIR", title_ar: "عامر", kind: "Warehouse AGV · patent", kind_ar: "روبوت مستودعات · براءة", year: "2022",
    blurb: "Autonomous mobile robot for warehouse logistics — low-profile tote-carrier with onboard navigation. Granted industrial-design patent.",
    blurb_ar: "روبوت متحرّك مستقل لخدمات المستودعات — حامل صناديق منخفض مع ملاحة ذاتية. حاصل على براءة تصميم صناعي." },
  { id: "proj-robohotel", cat: "ground", title: "RoboHotel", title_ar: "روبو-هوتيل", kind: "Service robot · patent", kind_ar: "روبوت خدمة · براءة", year: "2022",
    blurb: "A bellhop service robot for hotels: luggage-carrying AMR with a guest touchscreen and a hospitality-grade shell.",
    blurb_ar: "روبوت خدمة للفنادق بدور الحمّال: روبوت متحرّك يحمل الأمتعة بشاشة لمس للنزلاء وهيكلٍ بمستوى الضيافة." },
  { id: "proj-faseeh", cat: "ground", title: "FASEEH", title_ar: "فصيح", kind: "Outdoor UGV", kind_ar: "روبوت أرضي خارجي", year: "2023",
    blurb: "Rugged Ackermann-steered ground vehicle with long-travel suspension for outdoor autonomy on uneven terrain.",
    blurb_ar: "مركبة أرضية صلبة بتوجيه أكرمان وتعليق طويل المدى للاستقلالية الخارجية على التضاريس الوعرة." },
  { id: "proj-agridrone", cat: "aerial", title: "AgriDrone", title_ar: "درون زراعي", kind: "Spraying hexacopter", kind_ar: "سداسية رشّ", year: "2023",
    blurb: "A heavy-lift agricultural hexacopter for precision spraying and palm-tree survey, designed around a carbon-fiber payload bay.",
    blurb_ar: "طائرة سداسية ثقيلة الحمولة للرشّ الدقيق ومسح أشجار النخيل، مُصمّمة حول حجيرة حمولة من ألياف الكربون." },
  { id: "proj-surveil", cat: "aerial", title: "Surveillance Drone", title_ar: "درون مراقبة", kind: "Custom hexacopter", kind_ar: "سداسية مخصّصة", year: "2022",
    blurb: "A custom hexacopter with a stabilized gimbal payload for aerial inspection and tracking research.",
    blurb_ar: "طائرة سداسية مخصّصة بحمولة مثبّتة بالجيمبال للتفتيش الجوي وأبحاث التتبّع." },
];

export const PAPERS = [
  { year: "2026", title: "ROS 2 in a Nutshell: A Survey", venue: "ACM Computing Surveys", role: "First author", role_ar: "المؤلف الأول",
    doi: "https://doi.org/10.1145/3815113", tag: "ROS 2" },
  { year: "2026", title: "Two-Stage Residual EKF with XGBoost & KAN for GNSS-denied UAV Localization", venue: "Engineering Applications of AI", role: "Co-author", role_ar: "مؤلف مشارك",
    doi: "https://doi.org/10.1016/j.engappai.2026.114430", tag: "Localization" },
  { year: "2025", title: "GNSS-Denied UAV Navigation: Complexity, Sensor Fusion & Localization", venue: "Satellite Navigation", role: "Co-author", role_ar: "مؤلف مشارك",
    doi: "https://doi.org/10.1186/s43020-025-00162-z", tag: "Localization" },
  { year: "2025", title: "Palm: A Culturally Inclusive Dataset for Arabic LLMs", venue: "ACL 2025 (Vienna)", role: "Contributor", role_ar: "مساهم",
    doi: "https://doi.org/10.18653/v1/2025.acl-long.1579", tag: "Arabic NLP" },
  { year: "2025", title: "VECTOR: Velocity-Enhanced GRU for Real-Time 3D UAV Trajectory Prediction", venue: "Drones (MDPI)", role: "Co-author", role_ar: "مؤلف مشارك",
    doi: "https://doi.org/10.3390/drones9010008", tag: "Prediction" },
  { year: "2025", title: "FLIGHTGEN: ROS 2-Powered Automated UAV Dataset Generator", venue: "SmartSE (Springer)", role: "Co-author", role_ar: "مؤلف مشارك",
    doi: "https://doi.org/10.1007/978-3-031-91235-1_28", tag: "Simulation" },
  { year: "2024", title: "D2DTracker: Real-Time Trajectory Prediction for Drone-to-Drone Tracking", venue: "UVS 2024 (IEEE)", role: "Co-author", role_ar: "مؤلف مشارك",
    doi: "https://doi.org/10.1109/UVS59630.2024.10467173", tag: "Tracking" },
];

export const RESEARCH_NOTE = "10 published (8 peer-reviewed + 2 preprints) · 4 accepted (incl. 3 Springer chapters) · 3 under review · 5 uncredited framework contributions.";
export const RESEARCH_NOTE_AR = "١٠ منشورة (٨ محكّمة + بحثان قيد الطبع) · ٤ مقبولة (منها ٣ فصول كتب من Springer) · ٣ قيد المراجعة · ٥ مساهمات إطارية غير منسوبة.";

/* ── The path so far: education + career milestones (2018 → now) ──
   Drives the glowing scroll-path on Home. kind: edu | work | milestone | next. */
export const JOURNEY = [
  { year: "2018", kind: "edu", tag: "M.Sc.", tag_ar: "ماجستير",
    title: "Began M.Sc. in Robotics & Autonomous Intelligent Systems", title_ar: "بدء ماجستير الروبوتات والأنظمة الذكية المستقلة",
    org: "KFUPM · Dhahran", org_ar: "جامعة الملك فهد للبترول والمعادن · الظهران",
    note: "Turned a childhood inventor's dream into control loops, estimators, and airframes.",
    note_ar: "تحويل حلم الطفولة بالاختراع إلى حلقات تحكّم ومُقدِّرات وهياكل طائرات." },
  { year: "2019", kind: "work", tag: "Industry", tag_ar: "صناعة",
    title: "Aircraft Maintenance Engineer", title_ar: "مهندس صيانة طائرات",
    org: "Saudia Aerospace Engineering Industries (SAEI) · Jeddah", org_ar: "الصناعات الهندسية الجوية السعودية (SAEI) · جدة",
    note: "Recovered SAR 21M in lost invoices · −70% NEF defects · KPI dashboards cut analysis time 96%.",
    note_ar: "استرداد ٢١ مليون ريال · خفض العيوب ٧٠٪ · لوحات مؤشرات خفضت زمن التحليل ٩٦٪." },
  { year: "2021", kind: "edu", tag: "Graduated", tag_ar: "تخرّج",
    title: "M.Sc. completed — with honors (GPA 3.6 / 4.0)", title_ar: "إتمام الماجستير — مع مرتبة الشرف (٣٫٦ / ٤)",
    org: "KFUPM · Robotics & AIS", org_ar: "جامعة الملك فهد · الروبوتات والأنظمة الذكية",
    note: "Thesis-grade work in UAV autonomy and state estimation.",
    note_ar: "عمل بمستوى الرسالة في استقلالية الطائرات وتقدير الحالة." },
  { year: "2022", kind: "work", tag: "Research", tag_ar: "بحث",
    title: "Senior Research Assistant", title_ar: "باحث أول",
    org: "Prince Sultan University · Robotics & IoT Lab (RIOTU)", org_ar: "جامعة الأمير سلطان · معمل الروبوتات وإنترنت الأشياء",
    note: "Lead robotics R&D — UAV/UGV, GPS-denied localization, agentic multi-robot systems. Teach CS460; run drone & ROS 2 workshops.",
    note_ar: "قيادة البحث والتطوير — طائرات وروبوتات أرضية، تموضع دون GPS، منظومات وكيلة متعددة الروبوتات. تدريس CS460 وورش الدرون وROS 2." },
  { year: "2026", kind: "milestone", tag: "Milestone", tag_ar: "محطة",
    title: "10 papers · 2 patents · 8 robots", title_ar: "١٠ أبحاث · براءتان · ٨ روبوتات",
    org: "ACM Computing Surveys · IEEE · Springer · ACL", org_ar: "ACM Computing Surveys · IEEE · Springer · ACL",
    note: "First-author ROS 2 survey (IF ≈ 28) · patented VIO kit · quadruped and GNSS-denied research maturing.",
    note_ar: "مسح ROS 2 كمؤلف أول · عُدّة تموضع مُبرّأة · نضوج أبحاث الرباعيات والتموضع دون GNSS." },
  { year: "2027", kind: "next", tag: "Incoming", tag_ar: "قادم",
    title: "Ph.D. in Mechanical Engineering — incoming", title_ar: "دكتوراه الهندسة الميكانيكية — قادمة",
    org: "KFUPM · Dynamics & Control", org_ar: "جامعة الملك فهد · الديناميكا والتحكّم",
    note: "Geometric-control thesis lean: Lie-theoretic estimation and safe control for field robots.",
    note_ar: "توجّه نحو التحكّم الهندسي: تقدير قائم على نظرية لي وتحكّم آمن لروبوتات الميدان." },
];

/* ── Research-interests map (Ramy-style): 4 overlapping domains around a
   shared focus, each carrying his representative work. Rendered as an
   interactive SVG on the Research page. ── */
export const RESEARCH_MAP = {
  center: { label: "Autonomous robots", label_ar: "روبوتات مستقلة",
    sub: "aerial · ground · legged", sub_ar: "جوية · أرضية · رباعية" },
  domains: [
    { id: "percept", pos: "tl", color: "#2f6b4f",
      label: "Perception & Estimation", label_ar: "الإدراك وتقدير الحالة",
      topics: ["GNSS-denied localization", "VIO · SLAM", "EKF / sensor fusion", "learned estimators"],
      topics_ar: ["التموضع دون GNSS", "VIO · SLAM", "EKF ودمج الحساسات", "مُقدِّرات متعلَّمة"],
      work: "GNSS-denied UAV navigation survey · Two-Stage Residual EKF (XGBoost·KAN) · RoboEye VIO kit (patented).",
      work_ar: "مسح الملاحة دون GNSS · مرشّح كالمان ببقايا على مرحلتين (XGBoost·KAN) · عُدّة RoboEye المُبرّأة." },
    { id: "learn", pos: "tr", color: "#b6803a",
      label: "Learning & AI", label_ar: "التعلّم والذكاء الاصطناعي",
      topics: ["reinforcement learning", "trajectory prediction (GRU)", "agentic AI · LLM planning", "Arabic NLP · generative 3D"],
      topics_ar: ["التعلّم المعزّز", "توقّع المسار (GRU)", "الذكاء الوكيل · تخطيط LLM", "معالجة العربية · توليد ثلاثي الأبعاد"],
      work: "VECTOR trajectory prediction · QuadroRL · SAFEMRS LLM-plan safety · PALM Arabic dataset (ACL A*).",
      work_ar: "توقّع المسار VECTOR · QuadroRL · سلامة خطط LLM في SAFEMRS · بيانات PALM العربية (ACL A*)." },
    { id: "control", pos: "bl", color: "#3f7a86",
      label: "Control & Planning", label_ar: "التحكّم والتخطيط",
      topics: ["motion planning", "geometric / nonlinear control", "behavior trees · FSM", "interception & tracking"],
      topics_ar: ["تخطيط الحركة", "تحكّم هندسي / لاخطي", "أشجار السلوك · آلات الحالة", "الاعتراض والتتبّع"],
      work: "D2DTracker drone-to-drone tracking · RL interception · geometric-control Ph.D. track (Lie theory on SE(3)).",
      work_ar: "تتبّع درون-بدرون D2DTracker · اعتراض بالتعلّم المعزّز · مسار دكتوراه التحكّم الهندسي (نظرية لي على SE(3))." },
    { id: "systems", pos: "br", color: "#8a6d2f",
      label: "Systems & Simulation", label_ar: "الأنظمة والمحاكاة",
      topics: ["ROS 2 · middleware", "Gazebo · PX4 · Sim2Real", "digital twins", "benchmarking · datasets"],
      topics_ar: ["ROS 2 والوسطيات", "Gazebo · PX4 · Sim2Real", "التوائم الرقمية", "القياس ومجموعات البيانات"],
      work: "ROS 2 survey (first author, IF ≈ 28) · FLIGHTGEN generator · ROSNavBench · modular digital-twin framework.",
      work_ar: "مسح ROS 2 (مؤلف أول، IF ≈ 28) · مولّد FLIGHTGEN · ROSNavBench · إطار توأم رقمي معياري." },
  ],
  platforms: [
    { label: "UAV — VTOL · multirotor", label_ar: "طائرات — VTOL · متعددة المراوح" },
    { label: "UGV — rover · warehouse AGV", label_ar: "أرضية — روفر · روبوت مستودعات" },
    { label: "Legged — Unitree Go2", label_ar: "رباعية — Unitree Go2" },
  ],
};

export const ROBOTS = [
  { id: "proj-vtol-build", cap: "VTOL UAV — final assembly in the lab", cap_ar: "طائرة VTOL — التجميع النهائي في المعمل" },
  { id: "rob-psu-hexa",    cap: "PSU Robotics & IoT Lab hexacopter — exhibition build", cap_ar: "سداسية معمل الروبوتات بجامعة الأمير سلطان — نسخة المعرض" },
  { id: "rob-quad-gym",    cap: "Research quadrotor — flight-test platform", cap_ar: "رباعية بحثية — منصة اختبار الطيران" },
  { id: "rob-ugv-proto",   cap: "Indoor differential-drive UGV — early prototype", cap_ar: "روبوت أرضي داخلي تفاضلي الدفع — نموذج أولي" },
  { id: "rob-gimbal",      cap: "Stabilized GoPro gimbal payload", cap_ar: "حمولة جيمبال مثبّتة لكاميرا GoPro" },
  { id: "rob-quad-elec",   cap: "Custom flight-controller stack — wiring detail", cap_ar: "منظومة تحكّم طيران مخصّصة — تفاصيل التوصيل" },
  { id: "rob-bench",       cap: "The workshop bench — fixed-wing fleet in progress", cap_ar: "طاولة الورشة — أسطول ثابت الجناح قيد البناء" },
  { id: "proj-surveil",    cap: "Custom surveillance hexacopter — studio", cap_ar: "سداسية مراقبة مخصّصة — استوديو" },
];

export const PRINTS = [
  { id: "print-stereo",  cap: "RoboEye stereo-camera enclosure — 125 g, printed in PETG", cap_ar: "حاوية كاميرا RoboEye الثنائية — ١٢٥ غرامًا، مطبوعة من PETG" },
  { id: "print-kacst-1", cap: "Functional prints — impeller, housing, mechanisms (KACST Industry 4.0)", cap_ar: "مطبوعات وظيفية — مروحة، حاوية، آليّات (كاكست للصناعة ٤٫٠)" },
  { id: "print-kacst-2", cap: "Engine piston, turbine & centrifugal housing — printed for testing", cap_ar: "مكبس محرّك وتوربين وحاوية طاردة مركزية — مطبوعة للاختبار" },
  { id: "patent-vtol",   cap: "1:7 VTOL prototype — scale model", cap_ar: "نموذج طائرة VTOL بمقياس ١:٧" },
];

export const PATENTS = [
  { id: "patent-transfer", title: "Transfer Robots (AMIR)", title_ar: "روبوتات النقل (عامر)",
    body: "Granted industrial-design certificate — Saudi Authority for Intellectual Property. Autonomous transfer robots for warehouses & hotels.",
    body_ar: "شهادة تصميم صناعي ممنوحة — الهيئة السعودية للملكية الفكرية. روبوتات نقل ذاتية للمستودعات والفنادق.", year: "2023" },
  { id: "print-stereo", title: "RoboEye — VIO Localization Kit", title_ar: "عين الروبوت — حساس التموضع البصري-القصوري",
    body: "Granted industrial-design certificate — Saudi Authority for Intellectual Property. A visual-inertial odometry kit for GPS-denied robot localization.",
    body_ar: "شهادة تصميم صناعي ممنوحة — الهيئة السعودية للملكية الفكرية. حساس قياس بصري-قصوري لتموضع الروبوت في الأماكن المحرومة من GPS.", year: "2024" },
];

export const EXPERIENCE = [
  { when: "2022 — now", when_ar: "٢٠٢٢ — الآن", role: "Senior Research Assistant", role_ar: "باحث أول", org: "Prince Sultan University · Robotics & IoT Lab (RIOTU)", org_ar: "جامعة الأمير سلطان · معمل الروبوتات وإنترنت الأشياء",
    note: "Lead robotics R&D — UAV/UGV design, GPS-denied localization (PSDSARC defense collaboration), agentic-AI multi-robot systems, generative 3D for manufacturing. Teach CS460 Mobile Robots; run drone & ROS 2 workshops.",
    note_ar: "قيادة البحث والتطوير في الروبوتات — تصميم طائرات وروبوتات أرضية، التموضع دون GPS (بالتعاون مع مركز الأمير سلطان للدراسات الدفاعية)، منظومات روبوتات متعددة بالذكاء الوكيل، التوليد ثلاثي الأبعاد للتصنيع. تدريس مقرر CS460 وإقامة ورش الدرون وROS 2." },
  { when: "2019 — 2021", when_ar: "٢٠١٩ — ٢٠٢١", role: "Aircraft Maintenance Engineer", role_ar: "مهندس صيانة طائرات", org: "Saudia Aerospace Engineering Industries (SAEI), Jeddah", org_ar: "الصناعات الهندسية الجوية السعودية (SAEI)، جدة",
    note: "Recovered SAR 21M in lost invoices; cut analysis time 96% with KPI dashboards; led a defect-reduction project (−70% NEF defects).",
    note_ar: "استرداد ٢١ مليون ريال من فواتير مفقودة؛ خفض زمن التحليل ٩٦٪ عبر لوحات مؤشرات؛ قيادة مشروع خفض العيوب بنسبة ٧٠٪." },
  { when: "2017", when_ar: "٢٠١٧", role: "Production Engineering Trainee", role_ar: "متدرّب هندسة إنتاج", org: "KACST Innovative Centre for Industry 4.0", org_ar: "مركز كاكست الابتكاري للصناعة ٤٫٠",
    note: "PLC processes, CAD/CAM/CAE with NX11, CNC machining.",
    note_ar: "عمليات PLC، وتصميم وتصنيع وتحليل CAD/CAM/CAE عبر NX11، وتشغيل CNC." },
];

export const EDUCATION = [
  { when: "2018 — 2021", when_ar: "٢٠١٨ — ٢٠٢١", deg: "M.Sc. Robotics & Autonomous Intelligent Systems", deg_ar: "ماجستير الروبوتات والأنظمة الذكية المستقلة", org: "KFUPM · Dhahran", org_ar: "جامعة الملك فهد للبترول والمعادن · الظهران", extra: "GPA 3.6 / 4.0 · with honors", extra_ar: "المعدّل ٣٫٦ / ٤ · مع مرتبة الشرف" },
  { when: "2014 — 2018", when_ar: "٢٠١٤ — ٢٠١٨", deg: "B.Sc. Mechanical Engineering", deg_ar: "بكالوريوس الهندسة الميكانيكية", org: "KFUPM · Dhahran", org_ar: "جامعة الملك فهد للبترول والمعادن · الظهران", extra: "GPA 3.5 / 4.0 · with honors", extra_ar: "المعدّل ٣٫٥ / ٤ · مع مرتبة الشرف" },
  { when: "2016", when_ar: "٢٠١٦", deg: "Exchange — Mechanical Engineering", deg_ar: "تبادل طلابي — الهندسة الميكانيكية", org: "Colorado School of Mines · USA", org_ar: "كلية كولورادو للمناجم · الولايات المتحدة", extra: "", extra_ar: "" },
];

export const SKILLS = [
  { group: "CAD & Design", group_ar: "التصميم الهندسي CAD",
    items: ["SolidWorks", "Siemens NX", "Assemblies & drawings", "Generative design", "CAD → URDF / mesh pipelines"],
    items_ar: ["SolidWorks", "Siemens NX", "التجميعات والرسومات الهندسية", "التصميم التوليدي", "تحويل CAD إلى URDF ومجسّمات"] },
  { group: "3D Printing & Fabrication", group_ar: "الطباعة ثلاثية الأبعاد والتصنيع",
    items: ["FDM — PLA · PETG", "Design for additive (MIT xPRO)", "Rapid prototyping", "Carbon-fiber builds", "CNC & workshop"],
    items_ar: ["طباعة FDM — PLA · PETG", "التصميم للتصنيع الإضافي (MIT xPRO)", "النمذجة السريعة", "هياكل ألياف الكربون", "CNC والورشة"] },
  { group: "Modeling & Simulation", group_ar: "النمذجة والمحاكاة",
    items: ["Dynamics & vibration", "MATLAB · Simulink", "COMSOL", "Gazebo · PX4 SITL", "Digital twins"],
    items_ar: ["الديناميكا والاهتزازات", "MATLAB · Simulink", "COMSOL", "Gazebo · PX4 SITL", "التوائم الرقمية"] },
  { group: "Robotics & Autonomy", group_ar: "الروبوتات والاستقلالية",
    items: ["ROS 2 / middleware", "UAV · UGV · quadruped (Go2) autonomy", "SLAM · VIO · EKF fusion", "PX4 · MAVROS offboard", "Multi-robot & MARL"],
    items_ar: ["ROS 2 والوسطيات", "استقلالية الطائرات والروبوتات الأرضية والرباعية (Go2)", "SLAM · VIO · دمج EKF", "تحكّم خارجي PX4 · MAVROS", "روبوتات متعددة و MARL"] },
  { group: "AI / ML", group_ar: "الذكاء الاصطناعي",
    items: ["Reinforcement learning", "Trajectory prediction (GRU)", "XGBoost · KAN estimators", "Agentic AI & LLM systems", "Arabic NLP datasets"],
    items_ar: ["التعلّم المعزّز", "توقّع المسار (GRU)", "مُقدِّرات XGBoost · KAN", "الذكاء الوكيل وأنظمة LLM", "بيانات المعالجة العربية"] },
  { group: "Software", group_ar: "البرمجة والأدوات",
    items: ["Python", "C++", "Docker · Git · Linux", "LaTeX", "Simulation pipelines"],
    items_ar: ["Python", "C++", "Docker · Git · Linux", "LaTeX", "خطوط المحاكاة"] },
];

export const REPOS = [
  { name: "uavros2_docker", lang: "Shell", stars: 4, desc: "Dockerized ROS 2 stack for UAV development.", desc_ar: "حزمة ROS 2 مُحوّاة بـDocker لتطوير الطائرات.", url: "https://github.com/asmbatati/uavros2_docker" },
  { name: "uavros2", lang: "Python", stars: 3, desc: "ROS 2 packages for UAV autonomy.", desc_ar: "حزم ROS 2 لاستقلالية الطائرات.", url: "https://github.com/asmbatati/uavros2" },
  { name: "ros2_mavros", lang: "Python", stars: 3, desc: "ROS 2 Humble offboard UAV control via MAVROS.", desc_ar: "تحكّم خارجي بالطائرات عبر MAVROS على ROS 2 Humble.", url: "https://github.com/asmbatati/ros2_mavros" },
  { name: "awesome-ros", lang: "Python", stars: 1, desc: "Community dataset of the ROS ecosystem.", desc_ar: "مجموعة بيانات مجتمعية لمنظومة ROS.", url: "https://github.com/asmbatati/awesome-ros" },
  { name: "d2dtracker_interception", lang: "Python", stars: 1, desc: "Drone-to-drone trajectory interception in ROS 2.", desc_ar: "اعتراض مسار درون بدرون في ROS 2.", url: "https://github.com/asmbatati/d2dtracker_interception" },
  { name: "text-3d-printing", lang: "TypeScript", stars: 0, desc: "Type a name, print it — browser text-to-STL, printable across meshes.", desc_ar: "اكتب اسمًا فتُطبعه — تحويل نصّ إلى STL في المتصفّح.", url: "https://github.com/asmbatati/text-3d-printing" },
  { name: "AeroGym-PX4", lang: "Python", stars: 0, desc: "A PX4 reinforcement-learning gym for UAV control.", desc_ar: "بيئة تعلّم معزّز على PX4 للتحكّم بالطائرات.", url: "https://github.com/asmbatati/AeroGym-PX4" },
  { name: "SAFEMRS", lang: "TeX", stars: 0, desc: "Safe agentic framework for LLM-planned multi-robot systems.", desc_ar: "إطار وكيلي آمن لأنظمة روبوتات متعددة مخطّطة بـLLM.", url: "https://github.com/asmbatati/SAFEMRS" },
  { name: "cad_2_mesh", lang: "Python", stars: 0, desc: "CAD → mesh conversion for simulation pipelines.", desc_ar: "تحويل CAD إلى مجسّمات لخطوط المحاكاة.", url: "https://github.com/asmbatati/cad_2_mesh" },
  { name: "interception suite", lang: "C++ · Python", stars: 0, desc: "A 10-package D2DTracker stack: detection · estimation · prediction · planning · MPC control.", desc_ar: "منظومة D2DTracker من ١٠ حزم: كشف · تقدير · توقّع · تخطيط · تحكّم MPC.", url: "https://github.com/asmbatati?tab=repositories&q=interception" },
];

/* ── GitHub organizations I build under ── */
export const ORGS = [
  { name: "RIOTU-Lab", handle: "riotu-lab", role: "Robotics & IoT Lab · Prince Sultan University",
    role_ar: "معمل الروبوتات وإنترنت الأشياء · جامعة الأمير سلطان",
    desc: "Where my UAV autonomy, GPS-denied localization and multi-robot research ships.",
    desc_ar: "حيث تُنشر أبحاثي في استقلالية الطائرات والتموضع دون GPS والروبوتات المتعددة.",
    url: "https://github.com/riotu-lab", site: "https://riotu-lab.github.io" },
  { name: "NEUROS-X", handle: "neuros-x", role: "Agentic & safety-verified multi-robot systems",
    role_ar: "أنظمة روبوتات متعددة وكيلة ومُتحقَّقة السلامة",
    desc: "The program behind SAFEMRS — pre-execution safety for LLM-based robot task planning.",
    desc_ar: "البرنامج خلف SAFEMRS — سلامة ما قبل التنفيذ لتخطيط مهام الروبوتات بالنماذج اللغوية.",
    url: "https://github.com/neuros-x", site: "https://neuros-x.github.io/safemrs/" },
];

/* ── Teaching: courses + workshops I've taught (Teaching page) ── */
export const TEACHING = {
  courses: [
    { code: "CS460", title: "Mobile Robots", title_ar: "الروبوتات المتنقّلة",
      org: "Prince Sultan University", org_ar: "جامعة الأمير سلطان", when: "2022 — now", when_ar: "٢٠٢٢ — الآن",
      note: "Teaching assistant / instructor — ROS 2, motion planning, SLAM, and hands-on autonomous-robot labs.",
      note_ar: "معيد / مُحاضر — ROS 2 وتخطيط الحركة وSLAM ومختبرات عملية للروبوتات المستقلة.", tags: ["ROS 2", "SLAM", "planning"] },
    { code: "ME 218", title: "Engineering Design Process for Robotic Systems", title_ar: "منهجية التصميم الهندسي للأنظمة الروبوتية",
      org: "KFUPM (adapted from MIT 6.141)", org_ar: "جامعة الملك فهد (مقتبس من MIT 6.141)", when: "2024", when_ar: "٢٠٢٤",
      note: "Authored + delivered a 96-slide workshop on the robotics-modified engineering design process (digital-twin + Sim2Real stages).",
      note_ar: "تأليف وتقديم ورشة من ٩٦ شريحة حول منهجية التصميم الهندسي المعدّلة للروبوتات (مراحل التوأم الرقمي وSim2Real).", tags: ["design process", "V-model", "Sim2Real"] },
  ],
  workshops: [
    { title: "Managing a Fleet of Robots with ROS 2", title_ar: "إدارة أسطول روبوتات بـROS 2",
      org: "PSU · RIOTU Lab", org_ar: "جامعة الأمير سلطان · معمل RIOTU", when: "2023", when_ar: "٢٠٢٣",
      note: "Multi-robot coordination, namespacing, and Nav2 across a fleet — from bring-up to a shared world model.",
      note_ar: "تنسيق روبوتات متعددة والفضاءات الاسمية وNav2 عبر أسطول — من التشغيل إلى نموذج عالم مشترك.", tags: ["ROS 2", "Nav2", "multi-robot"] },
    { title: "Drone Building Workshop", title_ar: "ورشة بناء الطائرات المسيّرة",
      org: "PSU · outreach", org_ar: "جامعة الأمير سلطان · توعية", when: "2022 — 2024", when_ar: "٢٠٢٢ — ٢٠٢٤",
      note: "From frame + flight controller to a first PX4 flight — mechanical build, wiring, tuning, and safety.",
      note_ar: "من الهيكل ومتحكّم الطيران إلى أول إقلاع على PX4 — البناء الميكانيكي والتوصيل والضبط والسلامة.", tags: ["PX4", "hardware", "flight"] },
    { title: "Robotics & ROS 2 Bootcamps", title_ar: "معسكرات الروبوتات وROS 2",
      org: "PSU summer school", org_ar: "المدرسة الصيفية بجامعة الأمير سلطان", when: "2023 — 2024", when_ar: "٢٠٢٣ — ٢٠٢٤",
      note: "Intro-to-autonomy bootcamps: nodes, topics, TF, Gazebo simulation, and a capstone robot behavior.",
      note_ar: "معسكرات مقدّمة في الاستقلالية: العُقد والمواضيع وTF ومحاكاة Gazebo ومشروع سلوك روبوت ختامي.", tags: ["ROS 2", "Gazebo", "teaching"] },
  ],
  stats: [
    { n: "1", label: "university course", label_ar: "مقرّر جامعي" },
    { n: "4+", label: "workshops led", label_ar: "ورش قُدتها" },
    { n: "100+", label: "students & trainees", label_ar: "طالب ومتدرّب" },
    { n: "96", label: "slides authored (EDP)", label_ar: "شريحة من تأليفي (EDP)" },
  ],
};

/* ── Research taxonomy + full publications database ── */
export const TAXONOMY = [
  { id: "all", en: "All", ar: "الكل" },
  { id: "robotics", en: "Robotics Systems", ar: "أنظمة الروبوتات" },
  { id: "localization", en: "Localization & SLAM", ar: "التموضع والخرائط" },
  { id: "prediction", en: "Trajectory Prediction", ar: "توقّع المسار" },
  { id: "ros2", en: "ROS 2 & Middleware", ar: "ROS 2 والوسطيات" },
  { id: "sim", en: "Simulation & Sim2Real", ar: "المحاكاة" },
  { id: "nlp", en: "Arabic NLP", ar: "معالجة العربية" },
  { id: "gen3d", en: "3D / Generative", ar: "التوليد ثلاثي الأبعاد" },
  { id: "agentic", en: "Agentic AI", ar: "الذكاء الوكيل" },
];

export const PUBS = [
  // ── Published ──
  { title: "D2DTracker: A Framework for Real-Time Trajectory Prediction for Agile Drone-to-Drone Tracking via Adaptive Model Selection",
    status: "published", type: "Conference", venue: "2024 2nd Int. Conf. on Unmanned Vehicle Systems-Oman (UVS), IEEE", rank: "B", impact: "",
    doi: "https://doi.org/10.1109/UVS59630.2024.10467173", project: "", year: 2024, date: "Mar 2024",
    role: "2nd author · equal", role_ar: "ثاني المؤلفين · مساهمة متساوية", taxo: "prediction", tags: ["drone-to-drone", "tracking", "ROS", "Gazebo", "PX4"],
    abstract: "Real-time drone-to-drone tracking is crucial for protecting infrastructure and enforcing no-fly zones, but is hard when the target maneuvers agilely in 3D. D2DTracker fits a library of simple models to the target's recent behavior, generates multiple trajectory predictions in real time, and selects the best by least RMSE against live observations — repeating to adapt to changing behavior. Demonstrated in ROS + Gazebo + PX4, it reaches 0.2 RMSE on circular and infinity trajectories, with open-source packages provided.",
    abstract_ar: "إطار D2DTracker يولّد توقّعات آنية لمسار درون هدف عبر مطابقة مكتبة نماذج بسيطة واختيار الأفضل بأقل خطأ مقارنةً بالقياسات الحيّة، مُجرّبًا في ROS وGazebo وPX4.",
    bibtex: `@inproceedings{2024_D2DTrackerFramework_abdelkader,
  title = {{D2DTracker}: A Framework for Enabling Real-Time Trajectory Prediction for Agile Drone-to-Drone Tracking via Adaptive Model Selection},
  booktitle = {2024 2nd International Conference on Unmanned Vehicle Systems-Oman (UVS)},
  author = {Abdelkader, Mohamed and Al-Batati, Abdulrahman S. and Jarraya, Imen and Koubaa, Anis},
  date = {2024-02}, pages = {1--7}, doi = {10.1109/UVS59630.2024.10467173}
}` },
  { title: "Towards Inclusive Arabic LLMs: A Culturally Aligned Benchmark in Arabic Large Language Model Evaluation",
    status: "published", type: "Conference", venue: "LoResLM 2025 @ COLING, Association for Computational Linguistics", rank: "B", impact: "",
    doi: "https://aclanthology.org/2025.loreslm-1.29/", project: "", year: 2025, date: "Jan 2025",
    role: "Co-author", role_ar: "مؤلف مشارك", taxo: "nlp", tags: ["Arabic LLM", "benchmark", "evaluation", "cultural alignment"],
    abstract: "Arabic LLMs are usually judged on Western-centric benchmarks that overlook cultural context. This work evaluates the Arabic MMLU benchmark for cultural alignment: eleven experts annotated 2,500+ questions for fluency, adequacy, cultural appropriateness, bias, religious sensitivity, and social norms — surfacing significant misalignments, especially around religion and morality — and proposes annotation guidelines plus culturally enriched data to improve reliability.",
    abstract_ar: "تقييم معيار MMLU العربي من حيث المحاذاة الثقافية عبر تحكيم أحد عشر خبيرًا لأكثر من ٢٥٠٠ سؤال، مع كشف انحيازات ثقافية واقتراح إرشادات وبيانات أغنى.",
    bibtex: `@inproceedings{2025_InclusiveArabic_nacar,
  title = {Towards Inclusive Arabic LLMs: A Culturally Aligned Benchmark in Arabic Large Language Model Evaluation},
  booktitle = {Proceedings of the First Workshop on Language Models for Low-Resource Languages},
  author = {Nacar, Omer and Sibaee, Serry Taiseer and Ahmed, Samar and Ben Atitallah, Safa and Ammar, Adel and Alhabashi, Yasser and Al-Batati, Abdulrahman S. and Alsehibani, Arwa and Qandos, Nour and Elshehy, Omar and Abdelkader, Mohamed and Koubaa, Anis},
  date = {2025-01}, pages = {387--401}, publisher = {Association for Computational Linguistics}
}` },
  { title: "Palm: A Culturally Inclusive and Linguistically Diverse Dataset for Arabic LLMs",
    status: "published", type: "Conference", venue: "63rd Annual Meeting of the ACL (Long Papers), Vienna", rank: "A*", impact: "",
    doi: "https://doi.org/10.18653/v1/2025.acl-long.1579", project: "https://palm.dlnlp.ai/", year: 2025, date: "Jul 2025",
    role: "Co-author", role_ar: "مؤلف مشارك", taxo: "nlp", tags: ["Arabic LLM", "dataset", "22 countries", "MSA + dialects"],
    abstract: "PALM is a year-long, community-driven dataset covering all 22 Arab countries, built by 44 researchers. It contains instruction–response pairs in Modern Standard Arabic and dialectal Arabic across 20 topics, and is used to evaluate frontier LLMs' cultural and dialectal capabilities — revealing that closed-source models lead but still err, smaller open models struggle, and some countries are better represented than others.",
    abstract_ar: "مجموعة بيانات مجتمعية تغطّي ٢٢ دولة عربية بناها ٤٤ باحثًا، بأزواج تعليمات-استجابة بالفصحى واللهجات عبر ٢٠ موضوعًا، لتقييم القدرات الثقافية واللهجية للنماذج اللغوية.",
    bibtex: `@inproceedings{2025_PalmCulturally_alwajih,
  title = {Palm: A Culturally Inclusive and Linguistically Diverse Dataset for Arabic LLMs},
  booktitle = {Proceedings of the 63rd Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)},
  author = {Alwajih, Fakhraddin and others and Al-Batati, Abdulrahman S. and others and Abdul-Mageed, Muhammad},
  date = {2025-07}, pages = {32871--32894}, doi = {10.18653/v1/2025.acl-long.1579}, location = {Vienna, Austria}
}` },
  { title: "FLIGHTGEN: ROS 2-Powered Automated UAV Dataset Generator",
    status: "published", type: "Conference", venue: "SMARTTECH 2024, Springer LNNS vol. 1401", rank: "B", impact: "",
    doi: "https://doi.org/10.1007/978-3-031-91235-1_28", project: "", year: 2025, date: "2025",
    role: "Co-author", role_ar: "مؤلف مشارك", taxo: "sim", tags: ["ROS 2", "dataset", "simulation", "UAV"],
    abstract: "An automated, ROS 2-powered pipeline that generates labeled UAV flight datasets in simulation, easing the data bottleneck for training perception and prediction models.",
    abstract_ar: "خط أنابيب آلي بـROS 2 يولّد مجموعات بيانات طيران موسومة في المحاكاة لتدريب نماذج الإدراك والتوقّع.",
    bibtex: `@incollection{2025_FLIGHTGEN,
  title = {FLIGHTGEN: ROS2-Powered Automated UAV Dataset Generator},
  booktitle = {Smart Systems and Emerging Technologies (SMARTTECH 2024), LNNS vol. 1401},
  author = {Abdelkader, Mohamed and Gabr, Khaled and Al-Batati, Abdulrahman S. and Nacar, Omer and Jarraya, Imen and Koubaa, Anis},
  publisher = {Springer}, doi = {10.1007/978-3-031-91235-1_28}
}` },
  { title: "VECTOR: Velocity-Enhanced GRU Neural Network for Real-Time 3D UAV Trajectory Prediction",
    status: "published", type: "Journal", venue: "Drones, MDPI", rank: "Q1", impact: "",
    doi: "https://doi.org/10.3390/drones9010008", project: "", year: 2025, date: "Dec 2024",
    role: "Co-author", role_ar: "مؤلف مشارك", taxo: "prediction", tags: ["GRU", "trajectory", "real-time", "velocity"],
    abstract: "Most UAV trajectory predictors use only position and fail outside the training domain. VECTOR forecasts future velocity and position from historical velocity using GRUs, generalizing across position domains. Trained on synthetic (Gazebo + PX4) and real (UZH-FPV, Mid-Air) data, it reaches MSE of 2e-8 to 2e-7, beating state-of-the-art RNNs; the 5,000-trajectory dataset and a ROS 2 package are open-sourced.",
    abstract_ar: "شبكة GRU تتوقّع السرعة والموقع المستقبليين من تاريخ السرعة بدل الموقع، فتعمّم عبر مجالات الموقع وتتفوّق على الشبكات التكرارية، مع نشر مجموعة بيانات وحزمة ROS 2.",
    bibtex: `@article{2025_VECTORVelocityEnhanced_nacar,
  title = {VECTOR: Velocity-Enhanced GRU Neural Network for Real-Time 3D UAV Trajectory Prediction},
  author = {Nacar, Omer and Abdelkader, Mohamed and Ghouti, Lahouari and Gabr, Khaled and Al-Batati, Abdulrahman and Koubaa, Anis},
  date = {2025-01}, journaltitle = {Drones}, volume = {9}, number = {1}, pages = {8}, doi = {10.3390/drones9010008}
}` },
  { title: "GNSS-Denied UAV Navigation: Analyzing Computational Complexity, Sensor Fusion, and Localization Methodologies",
    status: "published", type: "Journal", venue: "Satellite Navigation, Springer", rank: "Q1", impact: "",
    doi: "https://doi.org/10.1186/s43020-025-00162-z", project: "https://riotu-lab.github.io/gps_denied_navigation_sim/", year: 2025, date: "Apr 2025",
    role: "2nd author · equal", role_ar: "ثاني المؤلفين · مساهمة متساوية", taxo: "localization", tags: ["GNSS-denied", "sensor fusion", "survey", "vision"],
    abstract: "An in-depth review of methods, sensors, and algorithms for outdoor UAV localization where GNSS is unavailable. It introduces a classification of GNSS-denied techniques into absolute vs relative localization, identifies vision-based methods as most effective, and argues no single-sensor approach suffices — a hybrid multi-sensor strategy is needed for reliable outdoor navigation.",
    abstract_ar: "مراجعة معمّقة لطرق وحساسات وخوارزميات تموضع الطائرات خارجيًا دون GNSS، مع تصنيف للتقنيات إلى مطلقة ونسبية، وترجيح الطرق البصرية وضرورة الدمج متعدّد الحساسات.",
    bibtex: `@article{2025_GnssdeniedUnmanned_jarraya,
  title = {GNSS-denied unmanned aerial vehicle navigation: analyzing computational complexity, sensor fusion, and localization methodologies},
  author = {Jarraya, Imen and Al-Batati, Abdulrahman and Kadri, Muhammad Bilal and Abdelkader, Mohamed and Ammar, Adel and Boulila, Wadii and Koubaa, Anis},
  date = {2025-04-07}, journaltitle = {Satellite Navigation}, volume = {6}, number = {1}, pages = {9}, doi = {10.1186/s43020-025-00162-z}
}` },
  { title: "A Two-Stage Residual EKF using XGBoost and Kolmogorov–Arnold Networks for Terrain-Aided UAV Localization in GNSS-Denied Environments",
    status: "published", type: "Journal", venue: "Engineering Applications of Artificial Intelligence, Elsevier", rank: "Q1", impact: "",
    doi: "https://doi.org/10.1016/j.engappai.2026.114430", project: "", year: 2026, date: "2026",
    role: "Co-author", role_ar: "مؤلف مشارك", taxo: "localization", tags: ["EKF", "XGBoost", "KAN", "terrain-aided", "ROS 2"],
    abstract: "The TSR-EKF fuses ML residual corrections into a probabilistic estimator: XGBoost removes coarse terrain/inertial bias, then Dense Kolmogorov–Arnold Networks refine the nonlinear residual, fused with IMU velocity and terrain-referenced measurements in an EKF. Validated on seven UAV trajectories over Taif, Saudi Arabia in high-fidelity Gazebo with real DEMs, it cuts RMSE by 57.4–98.9% vs traditional EKF while keeping sub-6 m accuracy and <2.1 ms per update.",
    abstract_ar: "مرشّح كالمان ببقايا على مرحلتين يدمج تصحيحات تعلّم آلي (XGBoost ثم شبكات كولموغوروف-أرنولد) مع قياسات التضاريس، فيخفض الخطأ ٥٧–٩٩٪ مع دقّة دون ٦ أمتار وزمن دون ٢٫١ ملّي ثانية.",
    bibtex: `@article{ABDELKADER2026114430,
  title = {A Two-Stage Residual Extended Kalman Filter using Extreme Gradient Boosting and Kolmogorov–Arnold Networks for terrain-aided UAV Localization in GNSS-denied environments},
  journal = {Engineering Applications of Artificial Intelligence}, volume = {173}, pages = {114430}, year = {2026},
  author = {Abdelkader, Mohamed and Jarraya, Imen and Gabr, Khaled and Al-Batati, Abdulrahman S. and AlMusalami, Abdullah and Alahmed, Fatimah and Boulila, Wadii},
  doi = {10.1016/j.engappai.2026.114430}
}` },
  // ── Accepted ──
  { title: "ROS 2 in a Nutshell: A Survey",
    status: "accepted", type: "Journal", venue: "ACM Computing Surveys", rank: "Q1", impact: "28",
    doi: "", project: "https://asmbatati.github.io/ros2_survey/", year: 2026, date: "2026",
    role: "1st author", role_ar: "المؤلف الأول", taxo: "ros2", tags: ["ROS 2", "survey", "middleware", "DDS"],
    abstract: "A comprehensive survey of the ROS 2 ecosystem — architecture, DDS middleware, real-time, security, lifecycle, and tooling — distilling thousands of sources into a single reference for roboticists. Accepted at ACM Computing Surveys (IF ≈ 28).",
    abstract_ar: "مسح شامل لمنظومة ROS 2 — المعمارية، DDS، الزمن الحقيقي، الأمان، الأدوات — يلخّص آلاف المصادر في مرجع واحد. مقبول في ACM Computing Surveys.", bibtex: "" },
  { title: "ACMS: A Multi-Agent Architecture for Automated CAD-to-Mesh Transformation using Tool-Based Reasoning",
    status: "accepted", type: "Book Chapter", venue: "The Rise of Agentic Intelligence: From Theory to Real-World Applications", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "2nd author · equal", role_ar: "ثاني المؤلفين · مساهمة متساوية",
    taxo: "gen3d", tags: ["agentic", "CAD-to-mesh", "tool reasoning"],
    abstract: "A multi-agent system that automates CAD-to-mesh conversion through tool-based reasoning, letting LLM agents orchestrate geometry pipelines for simulation-ready assets.",
    abstract_ar: "منظومة متعدّدة الوكلاء تؤتمت تحويل CAD إلى مجسّمات عبر استدلال بالأدوات، بحيث ينسّق وكلاء النماذج اللغوية خطوط الهندسة.", bibtex: "" },
  { title: "The Evolution of Generative AI in Meshes and CAD: From Geometric Modeling to Intelligent Design Systems",
    status: "accepted", type: "Book Chapter", venue: "Generative AI and LLMs — Volume 2", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "1st author", role_ar: "المؤلف الأول",
    taxo: "gen3d", tags: ["generative AI", "CAD", "design systems"],
    abstract: "A survey tracing generative AI for meshes and CAD — from classical geometric modeling to intelligent, language-driven design systems.",
    abstract_ar: "مسح يتتبّع الذكاء التوليدي للمجسّمات وCAD من النمذجة الهندسية الكلاسيكية إلى أنظمة تصميم ذكية مدفوعة باللغة.", bibtex: "" },
  { title: "Engineering Embodied Agents: A Modular ROS 2-Based Digital-Twin Framework for Heterogeneous Multi-Robot Systems",
    status: "accepted", type: "Book Chapter", venue: "Embodied Agents 2026 — The New Convergence of AI and Robotics", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "1st author", role_ar: "المؤلف الأول",
    taxo: "agentic", tags: ["digital twin", "ROS 2", "multi-robot"],
    abstract: "A modular ROS 2 digital-twin framework for heterogeneous multi-robot systems, bridging embodied AI agents with real robot fleets.",
    abstract_ar: "إطار توأم رقمي معياري بـROS 2 لمنظومات روبوتات غير متجانسة، يربط وكلاء الذكاء المُجسّد بأساطيل الروبوتات.", bibtex: "" },
  { title: "Generative 3D Object Modeling for Robust Robot Manipulation in ROS 2",
    status: "accepted", type: "Conference", venue: "2026 Int. Conf. on Advanced Robotics and Mechatronics (ICARM)", rank: "", impact: "",
    doi: "", project: "https://gen3d-research.github.io/3d_generator/", year: 2026, date: "2026", role: "1st author", role_ar: "المؤلف الأول",
    taxo: "gen3d", tags: ["generative 3D", "manipulation", "ROS 2"],
    abstract: "Generating 3D object models on demand to make ROS 2 robot manipulation robust to novel, unseen objects.",
    abstract_ar: "توليد مجسّمات ثلاثية الأبعاد عند الطلب لجعل مناولة الروبوت في ROS 2 صلبة أمام أجسام جديدة.", bibtex: "" },
  // ── Under review ──
  { title: "SAFEMRS: Corroborative Dual-Channel Pre-Execution Safety Verification for LLM-Based Heterogeneous Multi-Robot Task Planning",
    status: "review", type: "Conference", venue: "IROS 2026 (IEEE/RSJ)", rank: "", impact: "",
    doi: "", project: "https://neuros-x.github.io/safemrs/", year: 2026, date: "2026", role: "1st author", role_ar: "المؤلف الأول",
    taxo: "agentic", tags: ["safety", "multi-robot", "LLM planning"],
    abstract: "A dual-channel pre-execution safety verifier that corroborates LLM-generated multi-robot task plans before they run, catching unsafe plans early.",
    abstract_ar: "مُحقّق سلامة ثنائي القناة يتثبّت من خطط مهام الروبوتات المتعددة المولّدة من النماذج اللغوية قبل تنفيذها.", bibtex: "" },
  { title: "ROSNavBench: An Automated Benchmarking Suite for Evaluating Trajectory Planners in ROS 2 and Gazebo",
    status: "review", type: "Conference", venue: "IROS 2026", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "Co-author", role_ar: "مؤلف مشارك",
    taxo: "ros2", tags: ["benchmark", "Nav2", "planners", "Gazebo"],
    abstract: "An automated suite for benchmarking ROS 2 trajectory planners in Gazebo under standardized, reproducible scenarios.",
    abstract_ar: "حزمة آلية لقياس مخطّطات المسار في ROS 2 ضمن Gazebo بسيناريوهات قياسية قابلة للتكرار.", bibtex: "" },
  { title: "From Guidelines to Practice: A New Paradigm for Arabic Language Model Evaluation",
    status: "review", type: "Journal", venue: "ACM Trans. on Asian & Low-Resource Language Information Processing (TALLIP)", rank: "Q2", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "Co-author", role_ar: "مؤلف مشارك",
    taxo: "nlp", tags: ["Arabic", "evaluation", "guidelines"],
    abstract: "Turning culturally-aware annotation guidelines into a practical, scalable paradigm for evaluating Arabic language models.",
    abstract_ar: "تحويل إرشادات التحكيم المراعية للثقافة إلى منهجية عملية قابلة للتوسّع لتقييم النماذج العربية.", bibtex: "" },
  { title: "Anchor-Based Neural Network for City-Level UAV Geo-Localization under GNSS Signal Denial",
    status: "review", type: "Journal", venue: "Journal · under review", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "Co-author", role_ar: "مؤلف مشارك",
    taxo: "localization", tags: ["geo-localization", "GNSS-denied", "neural"],
    abstract: "An anchor-based neural network that geo-localizes UAVs at city scale without GNSS signals.",
    abstract_ar: "شبكة عصبية قائمة على المراسي تموضِع الطائرات على مستوى المدينة دون إشارات GNSS.", bibtex: "" },
  // ── In progress ──
  { title: "Toward Intelligent Quadruped Robots: A Survey of Perception, Locomotion, and Vision-Language-Action Models",
    status: "progress", type: "Journal", venue: "Survey · in progress", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "Lead author", role_ar: "المؤلف الرئيس",
    taxo: "robotics", tags: ["quadruped", "VLA", "locomotion", "survey"],
    abstract: "A systematic survey of perception, locomotion, and vision-language-action models for quadruped robots — toward general-purpose legged autonomy.",
    abstract_ar: "مسح منهجي للإدراك والحركة ونماذج الرؤية-اللغة-الفعل للروبوتات الرباعية نحو استقلالية عامة.", bibtex: "" },
  { title: "Search and Rescue Algorithms: A Categorization by Path Planning and Detection",
    status: "progress", type: "Journal", venue: "Journal · in progress", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "1st author", role_ar: "المؤلف الأول",
    taxo: "robotics", tags: ["search & rescue", "path planning", "detection"],
    abstract: "A taxonomy of search-and-rescue algorithms organized by path-planning and detection strategy.",
    abstract_ar: "تصنيف لخوارزميات البحث والإنقاذ بحسب تخطيط المسار والكشف.", bibtex: "" },
  { title: "QuadroRL: Learning Robust Terrain Traversal for Search and Rescue",
    status: "progress", type: "Journal", venue: "Journal · in progress", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "Co-author", role_ar: "مؤلف مشارك",
    taxo: "robotics", tags: ["RL", "quadruped", "terrain"],
    abstract: "Reinforcement learning for robust quadruped terrain traversal in search-and-rescue scenarios.",
    abstract_ar: "تعلّم معزّز لعبور التضاريس بمتانة بروبوت رباعي في مهام البحث والإنقاذ.", bibtex: "" },
  { title: "UAV RL-Based Interception",
    status: "progress", type: "Journal", venue: "Journal · in progress", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "1st author", role_ar: "المؤلف الأول",
    taxo: "robotics", tags: ["RL", "interception", "UAV"],
    abstract: "Reinforcement-learning policies for intercepting a maneuvering target drone.",
    abstract_ar: "سياسات تعلّم معزّز لاعتراض درون هدف مناور.", bibtex: "" },
  { title: "D2DTracker State Machine & Behaviour-Trees Interception",
    status: "progress", type: "Journal", venue: "Journal · in progress", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "1st author", role_ar: "المؤلف الأول",
    taxo: "prediction", tags: ["behaviour trees", "interception", "state machine"],
    abstract: "A behaviour-tree and state-machine layer over D2DTracker for end-to-end drone interception.",
    abstract_ar: "طبقة أشجار سلوك وآلة حالات فوق D2DTracker لاعتراض الدرون من طرف إلى طرف.", bibtex: "" },
  { title: "Smart-Predictor",
    status: "progress", type: "Journal", venue: "Journal · in progress", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "1st author", role_ar: "المؤلف الأول",
    taxo: "prediction", tags: ["prediction", "learning", "adaptive"],
    abstract: "An adaptive learned predictor for agile target trajectories.",
    abstract_ar: "مُتنبّئ متكيّف متعلَّم لمسارات الأهداف السريعة.", bibtex: "" },
  { title: "Text2UAV-URDF: Natural-Language Generation of UAV Robot Descriptions",
    status: "progress", type: "Journal", venue: "Journal · in progress", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "1st author", role_ar: "المؤلف الأول",
    taxo: "gen3d", tags: ["text-to-URDF", "generative", "UAV"],
    abstract: "Generating ready-to-simulate UAV URDF descriptions directly from natural language.",
    abstract_ar: "توليد أوصاف URDF للطائرات جاهزة للمحاكاة مباشرةً من اللغة الطبيعية.", bibtex: "" },
  { title: "Agentic ROS UAV Coordination",
    status: "progress", type: "Journal", venue: "Journal · in progress", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "1st author", role_ar: "المؤلف الأول",
    taxo: "agentic", tags: ["agentic", "multi-UAV", "ROS 2"],
    abstract: "Agentic-AI coordination of multiple UAVs over a ROS 2 stack.",
    abstract_ar: "تنسيق وكيل لعدّة طائرات فوق منظومة ROS 2.", bibtex: "" },
  { title: "XV-GeoLOCK: Cross-View UAV Geo-Localization",
    status: "progress", type: "Journal", venue: "Journal · in progress", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "2nd author", role_ar: "ثاني المؤلفين",
    taxo: "localization", tags: ["cross-view", "geo-localization"],
    abstract: "Cross-view matching for UAV geo-localization without satellite positioning.",
    abstract_ar: "مطابقة متعدّدة المنظور لتموضع الطائرات دون أقمار صناعية.", bibtex: "" },
  { title: "Benchmarking SLAM Algorithms for UAV Localization",
    status: "progress", type: "Journal", venue: "Journal · in progress", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "1st author", role_ar: "المؤلف الأول",
    taxo: "localization", tags: ["SLAM", "benchmark", "UAV"],
    abstract: "A systematic benchmark of SLAM algorithms for UAV localization.",
    abstract_ar: "قياس منهجي لخوارزميات SLAM لتموضع الطائرات.", bibtex: "" },
  { title: "A Dataset for SLAM Algorithms of UAV Localization",
    status: "progress", type: "Journal", venue: "Journal · in progress", rank: "", impact: "",
    doi: "", project: "", year: 2026, date: "2026", role: "1st author", role_ar: "المؤلف الأول",
    taxo: "localization", tags: ["SLAM", "dataset", "UAV"],
    abstract: "An open dataset to benchmark SLAM algorithms for UAV localization.",
    abstract_ar: "مجموعة بيانات مفتوحة لقياس خوارزميات SLAM لتموضع الطائرات.", bibtex: "" },
];

/* ── Robotics architecture — his real mental model (from his drawio) ──
   A closed perception↔decision loop around a shared world model, with a
   supervisory layer and three timing bands. Each node carries where his
   published / patented work lives. Rendered as an SVG schematic + cards. */
export const ARCH = {
  bands: [
    { id: "delib",  rate: "0.1–10 Hz",     ms: "100 ms – 10 s", label: "Deliberative", label_ar: "تداولي" },
    { id: "react",  rate: "10–50 Hz",      ms: "20–100 ms",     label: "Reactive",     label_ar: "تفاعلي" },
    { id: "reflex", rate: "100 Hz – 1 kHz", ms: "1–10 ms",      label: "Reflex",       label_ar: "انعكاسي" },
  ],
  nodes: {
    // ── Perception pipeline (left column, sensors → up) ──
    semantic: { col: "perc", band: "delib", label: "Semantic Perception", label_ar: "الإدراك الدلالي",
      sub: "Object detection · segmentation · scene understanding", sub_ar: "كشف الأجسام · التجزئة · فهم المشهد", mine: true,
      work: "Drone & object detection and tracking", work_ar: "كشف وتتبّع الطائرات والأجسام", papers: ["D2DTracker"] },
    spatial: { col: "perc", band: "react", label: "Spatial Perception & Mapping", label_ar: "الإدراك المكاني ورسم الخرائط",
      sub: "SLAM · point clouds · local maps", sub_ar: "SLAM · سُحُب النقاط · خرائط محلية", mine: true,
      work: "Visual-inertial odometry & local mapping (RoboEye, patented kit)", work_ar: "قياس بصري-قصوري ورسم خرائط محلي (RoboEye، عُدّة مُبرَّأة)", papers: ["RoboEye"] },
    stateest: { col: "perc", band: "reflex", label: "State Estimation & Sensor Fusion", label_ar: "تقدير الحالة ودمج الحساسات",
      sub: "Kalman filter · EKF · VIO", sub_ar: "مرشّح كالمان · EKF · VIO", mine: true,
      work: "GPS-denied localization · residual EKF · sensor fusion", work_ar: "تموضع دون GPS · مرشّح كالمان البقايا · دمج الحساسات", papers: ["TSR-EKF", "GNSS-Denied Nav"] },
    // ── Decision & control (right column, plans → down) ──
    task: { col: "cog", band: "delib", label: "Task Planning & Mission Control", label_ar: "تخطيط المهام والتحكّم بالمهمّة",
      sub: "Behavior trees · FSM · mission logic", sub_ar: "أشجار السلوك · آلات الحالة · منطق المهمّة", mine: true,
      work: "Agentic multi-UAV coordination & task allocation", work_ar: "تنسيق وكيلي لأسطول الطائرات وتوزيع المهام", papers: ["Agentic UAVs"] },
    motion: { col: "cog", band: "react", label: "Motion Planning & Local Navigation", label_ar: "تخطيط الحركة والملاحة المحلية",
      sub: "RRT · DWA · trajectory generation", sub_ar: "RRT · DWA · توليد المسارات", mine: true,
      work: "Trajectory prediction & planning for agile tracking", work_ar: "توقّع المسار والتخطيط للتتبّع السريع", papers: ["VECTOR", "D2DTracker"] },
    control: { col: "cog", band: "reflex", label: "Real-time Control", label_ar: "التحكّم اللحظي",
      sub: "PID · MPC · torque control", sub_ar: "PID · MPC · تحكّم بالعزم", mine: true,
      work: "Off-board UAV control via PX4 / MAVROS", work_ar: "تحكّم خارجي بالطائرات عبر PX4 / MAVROS", papers: ["PX4 · MAVROS"] },
    // ── Shared hub ──
    world: { col: "center", label: "Shared World Model", label_ar: "نموذج العالم المشترك",
      sub: "Semantic + geometric map · robot state · occupancy · dynamic obstacles · goals",
      sub_ar: "خريطة دلالية + هندسية · حالة الروبوت · الإشغال · العوائق المتحركة · الأهداف", mine: false },
    // ── Cross-cutting supervisor ──
    super: { col: "super", label: "Supervisory & Monitoring", label_ar: "الإشراف والمراقبة",
      sub: "Fault detection · plan validation · recovery · safety constraints", sub_ar: "كشف الأعطال · التحقّق من الخطة · التعافي · قيود السلامة", mine: true,
      work: "Runtime safety & benchmarking for multi-robot systems", work_ar: "سلامة زمن التشغيل وقياس الأداء لأنظمة متعددة الروبوتات", papers: ["SAFEMRS", "ROSNavBench"] },
    // ── Hardware layer ──
    sensors: { col: "hw", label: "Sensors", label_ar: "الحساسات", sub: "Cameras · LiDAR · IMU · encoders", sub_ar: "كاميرات · ليدار · IMU · مُرمِّزات", mine: true,
      work: "RoboEye sensor kit (patented)", work_ar: "عُدّة حساسات RoboEye (مُبرَّأة)", papers: ["RoboEye kit"] },
    actuators: { col: "hw", label: "Actuators", label_ar: "المُشغِّلات", sub: "Motors · ESCs · grippers", sub_ar: "محرّكات · مسرّعات · قابضات", mine: false },
    env: { col: "hw", label: "Dynamic Environment", label_ar: "البيئة الديناميكية", sub: "Moving obstacles · humans · changing conditions", sub_ar: "عوائق متحركة · بشر · ظروف متغيّرة", mine: false },
  },
  // signal paths shown in the legend
  legend: [
    { id: "flow",  label: "Standard flow",       label_ar: "التدفّق الأساسي" },
    { id: "share", label: "Shared world-model",  label_ar: "بيانات نموذج العالم" },
    { id: "react", label: "Reactive feedback",   label_ar: "تغذية راجعة تفاعلية" },
    { id: "emerg", label: "Emergency reflex",    label_ar: "ردّ فعل طارئ" },
  ],
  // sim-to-real footnote (his FLIGHTGEN / Gazebo work feeds the same loop)
  sim: "The whole loop is first closed in simulation — Gazebo / PX4-SITL worlds and the FLIGHTGEN automated dataset generator — before it ever flies.",
  sim_ar: "تُغلَق الحلقة كاملةً أولًا في المحاكاة — عوالم Gazebo / PX4-SITL ومولّد البيانات الآلي FLIGHTGEN — قبل أي طيران حقيقي.",
};

export const CALISTHENICS = {
  list: ["Muscle-ups", "Front lever", "Planche progressions", "Handstand", "Pull-ups", "Dips", "L-sit", "Pistol squats"],
  list_ar: ["العضلة المرتفعة", "الرافعة الأمامية", "تدرّجات البلانش", "الوقوف على اليدين", "العقلة", "الغطس", "جلسة L", "القرفصاء الأحادية"],
};

/* ── Blog: posts live in posts/*.md, indexed by posts/posts.json.
   Publish a vault note with:  python tools/publish_post.py "<path-to-note.md>"  ── */

/* ── Interactive interests gallery (page #gallery) ──
   5 ways (v9). Each cat.icon → img/gal/<icon>.webp (generated engraved icons). */
export const GALLERY = {
  cats: [
    { id: "caddesign", icon: "cad", label: "CAD & Design", label_ar: "التصميم CAD والهندسي",
      tease: "Parts, assemblies, whole machines", tease_ar: "قطع وتجميعات وآلات كاملة" },
    { id: "hardware", icon: "hardware", label: "Fabrication & Integration", label_ar: "التصنيع والدمج",
      tease: "Print, assemble, integrate", tease_ar: "طباعة وتجميع ودمج" },
    { id: "model", icon: "physics", label: "Physics & Math", label_ar: "الفيزياء والرياضيات",
      tease: "The theory under the machines", tease_ar: "النظرية خلف الآلات" },
    { id: "sim", icon: "sim", label: "Simulation", label_ar: "المحاكاة",
      tease: "ROS 2 worlds before flight", tease_ar: "عوالم ROS 2 قبل الطيران" },
    { id: "robotics", icon: "robotics", label: "Robotics", label_ar: "الروبوتات",
      tease: "My platforms — 3D + real", tease_ar: "منصّاتي — مجسّمة وحقيقية" },
  ],
  caddesign: {
    tools: ["SolidWorks", "Siemens NX", "Generative design", "cad_2_mesh"],
    images: [
      { id: "proj-taer", cap: "TAER — tilt-tail VTOL, full SolidWorks assembly", cap_ar: "طائر — VTOL بذيل دوّار، تجميع SolidWorks كامل" },
      { id: "proj-agridrone", cap: "AgriDrone — heavy-lift hexacopter, carbon payload bay", cap_ar: "الدرون الزراعي — سداسية ثقيلة بحجيرة كربونية" },
      { id: "proj-amir", cap: "AMIR — warehouse AGV, patented industrial design", cap_ar: "عامر — روبوت مستودعات بتصميم صناعي مُبرَّأ" },
      { id: "proj-robohotel", cap: "RoboHotel — hospitality shell over an AMR base", cap_ar: "روبو-هوتيل — هيكل ضيافة فوق قاعدة متحركة" },
      { id: "proj-faseeh", cap: "FASEEH — Ackermann UGV with long-travel suspension", cap_ar: "فصيح — مركبة أرضية بتوجيه أكرمان وتعليق طويل" },
      { id: "proj-roboeye", cap: "RoboEye — stereo-VIO enclosure, 125 g in PETG", cap_ar: "عين الروبوت — حاوية كاميرات ثنائية، ١٢٥ غرامًا" },
    ],
    projects: [
      { id: "proj-vtol-build", name: "VTOL UAV Platform", name_ar: "منصة VTOL", steps: [
        { t: "Concept", t_ar: "الفكرة", d: "A long-endurance mission needs both a helicopter's take-off and an airplane's cruise — so: a hybrid.", d_ar: "مهمة طويلة المدى تحتاج إقلاع المروحية وانسياب الطائرة — إذن: هجينة." },
        { t: "CAD", t_ar: "التصميم", d: "Full airframe in SolidWorks — lift quad booms over a fixed wing, sized around batteries and payload.", d_ar: "هيكل كامل في SolidWorks — أذرع رفع رباعية فوق جناح ثابت حول البطاريات والحمولة." },
        { t: "Build", t_ar: "التصنيع", d: "Carbon, foam and printed fittings, assembled and wired in-house at the lab.", d_ar: "كربون وفوم ووصلات مطبوعة، جُمّعت وسُلّكت داخل المعمل." },
        { t: "Flight", t_ar: "الطيران", d: "Hover, transition, cruise — the take-off that used to open this site was this aircraft's.", d_ar: "تحويم فانتقال فانسياب — الإقلاع الذي كان يفتتح الموقع كان لهذه الطائرة." } ] },
      { id: "proj-taer", name: "TAER", name_ar: "طائر", steps: [
        { t: "Concept", t_ar: "الفكرة", d: "Push endurance further: folding lift arms that tuck away in cruise, a tail that tilts.", d_ar: "مدًى أطول: أذرع رفع تنطوي أثناء الانسياب وذيل يميل." },
        { t: "CAD", t_ar: "التصميم", d: "Complete SolidWorks design — mechanisms, spars, control surfaces, mass budget.", d_ar: "تصميم SolidWorks كامل — آليّات وعوارض وأسطح تحكّم وميزانية كتلة." },
        { t: "Trade studies", t_ar: "المفاضلات", d: "Prop placement vs drag, arm-fold kinematics, tail-tilt authority — iterated on paper before metal.", d_ar: "موضع المراوح مقابل المقاومة، وحركيّة طيّ الأذرع — قبل أي تصنيع." },
        { t: "Status", t_ar: "الحالة", d: "A design-portfolio flagship; its ideas fed the built VTOL platform.", d_ar: "قطعة رئيسة في ملف التصميم؛ أفكارها غذّت المنصة المبنيّة." } ] },
      { id: "proj-roboeye", name: "RoboEye", name_ar: "عين الروبوت", steps: [
        { t: "Concept", t_ar: "الفكرة", d: "When GPS goes dark, robots go blind — package visual-inertial localization into one kit.", d_ar: "حين ينقطع GPS يعمى الروبوت — فلنحزم التموضع البصري-القصوري في عُدّة واحدة." },
        { t: "CAD", t_ar: "التصميم", d: "Stereo baseline, IMU seat and compute bay in a 125 g printable enclosure.", d_ar: "قاعدة كاميرتين ومقعد IMU وحجيرة معالجة في حاوية ١٢٥ غرامًا قابلة للطباعة." },
        { t: "Prototype", t_ar: "النموذج", d: "PETG prints on Raspberry Pi and Jetson — tested on UGVs and UAVs in GPS-denied rooms.", d_ar: "طباعة PETG على Raspberry Pi وJetson — اختُبرت داخليًا دون GPS." },
        { t: "Patent", t_ar: "البراءة", d: "Granted industrial-design certificate, Saudi Authority for Intellectual Property, 2024.", d_ar: "شهادة تصميم صناعي من الهيئة السعودية للملكية الفكرية، ٢٠٢٤." } ] },
      { id: "proj-amir", name: "AMIR", name_ar: "عامر", steps: [
        { t: "Concept", t_ar: "الفكرة", d: "Warehouse totes move all day — a low robot that slides under, lifts and delivers.", d_ar: "صناديق المستودعات تتحرك طوال اليوم — روبوت منخفض ينزلق تحتها ويرفعها." },
        { t: "CAD", t_ar: "التصميم", d: "Low-profile chassis, lift plate, sensor belt — designed for manufacture from day one.", d_ar: "هيكل منخفض وصفيحة رفع وحزام حساسات — مُصمَّم للتصنيع منذ اليوم الأول." },
        { t: "Prototype", t_ar: "النموذج", d: "Drive base with onboard navigation, tested on warehouse-style routes.", d_ar: "قاعدة دفع بملاحة ذاتية جُرّبت على مسارات مستودعية." },
        { t: "Patent", t_ar: "البراءة", d: "Granted industrial-design certificate (transfer robots), 2023.", d_ar: "شهادة تصميم صناعي (روبوتات النقل)، ٢٠٢٣." } ] },
      { id: "proj-robohotel", name: "RoboHotel", name_ar: "روبو-هوتيل", steps: [
        { t: "Concept", t_ar: "الفكرة", d: "A bellhop that never sleeps — luggage AMR with a guest-facing touchscreen.", d_ar: "حمّالٌ لا ينام — روبوت أمتعة بشاشة لمس للنزلاء." },
        { t: "CAD", t_ar: "التصميم", d: "Hospitality-grade shell over the AMIR drive experience — soft surfaces, service tray, screen mast.", d_ar: "هيكل بمستوى الضيافة فوق خبرة عامر — أسطح ناعمة وصينية خدمة وسارية شاشة." },
        { t: "Prototype", t_ar: "النموذج", d: "Guest-interaction flow mocked on the drive base with the real shell.", d_ar: "تدفّق تفاعل النزيل على القاعدة الحقيقية بالهيكل الفعلي." },
        { t: "Patent", t_ar: "البراءة", d: "Part of the granted transfer-robots industrial design family.", d_ar: "ضمن عائلة براءة روبوتات النقل الممنوحة." } ] },
      { id: "proj-faseeh", name: "FASEEH", name_ar: "فصيح", steps: [
        { t: "Concept", t_ar: "الفكرة", d: "Outdoor autonomy dies on curbs and rocks — build the suspension first.", d_ar: "الاستقلالية الخارجية تموت عند الأرصفة والصخور — فلنبدأ من التعليق." },
        { t: "CAD", t_ar: "التصميم", d: "Ackermann steering, long-travel arms, sealed electronics bay.", d_ar: "توجيه أكرمان وأذرع طويلة المدى وحجيرة إلكترونيات معزولة." },
        { t: "Build", t_ar: "التصنيع", d: "Welded and printed mix; drivetrain tuned for uneven terrain.", d_ar: "مزيج لحام وطباعة؛ منظومة دفع مضبوطة للتضاريس الوعرة." },
        { t: "Field", t_ar: "الميدان", d: "Outdoor navigation trials on gravel and sand.", d_ar: "تجارب ملاحة خارجية على الحصى والرمل." } ] },
      { id: "proj-agridrone", name: "AgriDrone", name_ar: "الدرون الزراعي", steps: [
        { t: "Concept", t_ar: "الفكرة", d: "Precision spraying for palm farms — heavy lift, gentle chemistry.", d_ar: "رشّ دقيق لمزارع النخيل — حمولة ثقيلة وكيمياء رفيقة." },
        { t: "CAD", t_ar: "التصميم", d: "Hexacopter frame around a carbon-fiber payload bay and tank.", d_ar: "إطار سداسي حول حجيرة حمولة وخزّان من ألياف الكربون." },
        { t: "Build", t_ar: "التصنيع", d: "Carbon arms, printed mounts, spray plumbing and pumps integrated.", d_ar: "أذرع كربونية وحوامل مطبوعة ومنظومة رشّ متكاملة." },
        { t: "Field", t_ar: "الميدان", d: "Spraying and palm-survey flights.", d_ar: "طلعات رشّ ومسح للنخيل." } ] },
      { id: "proj-surveil", name: "Surveillance Drone", name_ar: "درون المراقبة", steps: [
        { t: "Concept", t_ar: "الفكرة", d: "An aerial eye for inspection and tracking research.", d_ar: "عين جوية للتفتيش وأبحاث التتبّع." },
        { t: "CAD", t_ar: "التصميم", d: "Custom hexacopter sized around a stabilized gimbal payload.", d_ar: "سداسية مخصّصة حول حمولة جيمبال مثبّتة." },
        { t: "Build", t_ar: "التصنيع", d: "Frame, power train and gimbal integration in the lab.", d_ar: "إطار ومنظومة قدرة وتكامل الجيمبال في المعمل." },
        { t: "Research", t_ar: "البحث", d: "Flight platform behind the D2DTracker drone-tracking work.", d_ar: "منصة الطيران خلف أبحاث تتبّع الدرون D2DTracker." } ] },
    ],
  },
  robotics: {
    platforms: [
      { id: "vtol", photo: "proj-vtol-build", name: "VTOL hybrid UAV", name_ar: "طائرة VTOL هجينة",
        desc: "Vertical take-off, fixed-wing cruise. Designed, fabricated and flown in-house for long-endurance missions.",
        desc_ar: "إقلاع عمودي وانسياب ثابت الجناح. صُمّمت وصُنّعت وطارت داخليًا لمهام طويلة المدى.", tags: ["PX4", "long endurance"] },
      { id: "quad", photo: "rob-quad-gym", name: "Research quadrotor", name_ar: "رباعية بحثية",
        desc: "The flight-test workhorse behind the trajectory-prediction and interception papers.",
        desc_ar: "منصة اختبار الطيران خلف أبحاث توقّع المسار والاعتراض.", tags: ["D2DTracker", "VECTOR"] },
      { id: "hexa", photo: "proj-agridrone", name: "Heavy-lift hexacopter", name_ar: "سداسية ثقيلة الحمولة",
        desc: "Two builds: an agricultural sprayer with a carbon payload bay, and a gimbal-stabilized surveillance craft.",
        desc_ar: "نسختان: رشّاشة زراعية بحجيرة كربونية، وطائرة مراقبة بجيمبال مثبّت.", tags: ["AgriDrone", "gimbal"] },
      { id: "go2", name: "Quadruped — Unitree Go2", name_ar: "الروبوت الرباعي — Unitree Go2",
        desc: "The legged platform behind the quadruped perception · locomotion · VLA survey and the QuadroRL rough-terrain reinforcement-learning work.",
        desc_ar: "المنصة ذات الأرجل خلف مسح الروبوتات الرباعية (إدراك · حركة · نماذج VLA) وأعمال QuadroRL لعبور التضاريس بالتعلّم المعزّز.", tags: ["Go2", "RL locomotion", "VLA"] },
      { id: "rover", photo: "proj-faseeh", name: "FASEEH — outdoor UGV", name_ar: "فصيح — مركبة أرضية",
        desc: "Ackermann-steered rover with long-travel suspension for autonomy on uneven terrain.",
        desc_ar: "مركبة بتوجيه أكرمان وتعليق طويل المدى للاستقلالية على التضاريس الوعرة.", tags: ["Ackermann", "outdoor"] },
      { id: "agv", photo: "proj-amir", name: "AMIR — warehouse AGV", name_ar: "عامر — روبوت مستودعات",
        desc: "Low-profile tote-carrier with onboard navigation. Granted industrial-design patent.",
        desc_ar: "حامل صناديق منخفض بملاحة ذاتية. حاصل على براءة تصميم صناعي.", tags: ["patent", "logistics"] },
      { id: "bot", photo: "proj-robohotel", name: "RoboHotel — service robot", name_ar: "روبو-هوتيل — روبوت خدمة",
        desc: "A bellhop AMR: luggage deck, guest touchscreen, hospitality-grade shell.",
        desc_ar: "روبوت حمّال: سطح أمتعة وشاشة نزلاء وهيكل بمستوى الضيافة.", tags: ["patent", "service"] },
    ],
  },
  // Fabrication & Integration — real STLs rendered one-by-one as spotlit trophies + real print photos
  hardware: {
    intro: "Every part below is a real STL I designed and printed — mostly for the Tarot-960 drone build. Each spins under a spotlight; step through them.",
    intro_ar: "كل قطعة أدناه مجسّم STL حقيقي صمّمته وطبعته — أغلبها لبناء درون Tarot-960. تدور كلٌّ منها تحت ضوء كاشف؛ تنقّل بينها.",
    trophies: [
      { file: "tarot-cover.stl", name: "Tarot 960 top cover", name_ar: "غطاء Tarot 960 العلوي", note: "Electronics lid for the heavy-lift frame", note_ar: "غطاء إلكترونيات الهيكل ثقيل الحمولة" },
      { file: "payload-box.stl", name: "Modular payload box", name_ar: "صندوق حمولة معياري", note: "Split-print carrier for sensors & battery", note_ar: "حاوية مطبوعة مجزّأة للحساسات والبطارية" },
      { file: "xavier-holder.stl", name: "Jetson Xavier mount arm", name_ar: "ذراع تثبيت Jetson Xavier", note: "Onboard-compute holder for autonomy", note_ar: "حامل الحوسبة الطائرة للاستقلالية" },
      { file: "pcb-mount.stl", name: "Flight-controller PCB mount", name_ar: "حامل لوحة متحكّم الطيران", note: "Vibration-isolating board tray", note_ar: "صينية لوحة عازلة للاهتزاز" },
      { file: "holder-arm.stl", name: "Payload holder arm", name_ar: "ذراع حمل الحمولة", note: "Adjustable under-frame gimbal arm", note_ar: "ذراع جيمبال قابل للضبط أسفل الهيكل" },
      { file: "latch.stl", name: "Payload quick-latch", name_ar: "مزلاج الحمولة السريع", note: "Tool-free box release", note_ar: "تحرير الصندوق دون أدوات" },
      { file: "cover-bracket.stl", name: "Cover mounting bracket", name_ar: "كتيفة تثبيت الغطاء", note: "Snap bracket for the frame cover", note_ar: "كتيفة تعشيق لغطاء الهيكل" },
      { file: "calibration-cube.stl", name: "Printer calibration cube", name_ar: "مكعّب معايرة الطابعة", note: "Dimensional-accuracy test print", note_ar: "طبعة اختبار دقّة الأبعاد" },
    ],
    photos: [
      { id: "print-stereo", cap: "RoboEye stereo enclosure — PETG, 125 g", cap_ar: "حاوية عين الروبوت — PETG، ١٢٥ غ" },
      { id: "print-kacst-1", cap: "Impeller, housings, mechanisms — KACST Industry 4.0", cap_ar: "مروحة وحاويات وآليّات — كاكست للصناعة ٤٫٠" },
      { id: "print-kacst-2", cap: "Piston, turbine & centrifugal housing — printed for testing", cap_ar: "مكبس وتوربين وحاوية طاردة — للاختبار" },
      { id: "patent-vtol", cap: "1:7 VTOL prototype — scale model", cap_ar: "نموذج VTOL بمقياس ١:٧" },
    ],
  },
  // Physics & Math — a live demo + the theory that actually shows up in the work
  model: {
    intro: "Not decoration — this is the math I use. One live demo, and the theory behind the machines.",
    intro_ar: "ليست زينة — هذه هي الرياضيات التي أستعملها. عرضٌ حيّ واحد، والنظرية خلف الآلات.",
    topics: [
      { t: "Second-order dynamics", t_ar: "ديناميكا الدرجة الثانية", eq: "ẍ + 2ζωₙẋ + ωₙ²x = 0",
        note: "Every mount, arm and airframe rings like this — damping ζ and natural frequency ωₙ set how it settles. Live demo above.",
        note_ar: "كل حامل وذراع وهيكل يرنّ هكذا — التخميد ζ والتردد الطبيعي ωₙ يحدّدان كيف يستقرّ. العرض الحيّ أعلاه." },
      { t: "State estimation — Kalman / EKF", t_ar: "تقدير الحالة — كالمان / EKF", eq: "x̂ₖ = x̂ₖ⁻ + Kₖ (zₖ − h(x̂ₖ⁻))",
        note: "Fuse noisy sensors into one best estimate — the backbone of GPS-denied localization (TSR-EKF, RoboEye).",
        note_ar: "دمج حساسات ضوضائية في أفضل تقدير — العمود الفقري للتموضع دون GPS (TSR-EKF، RoboEye)." },
      { t: "Rigid-body rotation — SO(3)", t_ar: "دوران الجسم الصلب — SO(3)", eq: "Ṙ = R [ω]×,   R ∈ SO(3)",
        note: "Attitude lives on a manifold, not in Euler angles. The geometry my PhD leans into (Lie theory on SE(3)).",
        note_ar: "الاتّجاه يعيش على متعدّدة طيّات لا في زوايا أويلر. الهندسة التي تتوجّه إليها دكتوراتي (نظرية لي على SE(3))." },
      { t: "Rotational dynamics — Euler", t_ar: "الديناميكا الدورانية — أويلر", eq: "I ω̇ + ω × I ω = τ",
        note: "Why a quadrotor needs fast inner loops: cross-coupling torques you must fight in real time.",
        note_ar: "لماذا تحتاج الرباعية حلقات داخلية سريعة: عزوم اقتران يجب مقاومتها آنيًا." },
      { t: "Optimal control — LQR", t_ar: "التحكّم الأمثل — LQR", eq: "J = ∫ (xᵀQx + uᵀRu) dt",
        note: "Trade tracking error against effort — the cost that shapes smooth, stable trajectories.",
        note_ar: "موازنة خطأ التتبّع مقابل الجهد — الكلفة التي تصوغ مسارات سلسة مستقرّة." },
      { t: "Feedback control — PID", t_ar: "التحكّم بالتغذية الراجعة — PID", eq: "u = Kₚe + Kᵢ∫e + K_d ė",
        note: "The workhorse under PX4 — still the first loop I reach for on real hardware.",
        note_ar: "الحصان العامل تحت PX4 — لا تزال أول حلقة ألجأ إليها على العتاد الحقيقي." },
    ],
  },
  // Simulation — the ROS 2 sim + viz stack, plus a live GPS-denied estimate demo
  sim: {
    intro: "I close every loop in simulation first. The ROS 2 stack I reach for — and Rviz 2 to see what the robot believes.",
    intro_ar: "أُغلق كل حلقة في المحاكاة أولًا. منظومة ROS 2 التي أعتمدها — وRviz 2 لأرى ما يعتقده الروبوت.",
    simulators: [
      { name: "Gazebo (Harmonic + Classic)", note: "Primary physics sim, bridged to ROS 2 via ros_gz", note_ar: "محاكي الفيزياء الأساسي، موصولٌ بـROS 2 عبر ros_gz", tag: "physics" },
      { name: "PX4 SITL", note: "Software-in-the-loop for the flight stack — every UAV mission dry-runs here", note_ar: "برمجيات في الحلقة لمنظومة الطيران — كل مهمة طائرة تُجرّب هنا", tag: "flight" },
      { name: "NVIDIA Isaac Sim", note: "GPU-accelerated worlds for reinforcement learning (QuadroRL)", note_ar: "عوالم مُسرَّعة بالمعالج الرسومي للتعلّم المعزّز (QuadroRL)", tag: "RL" },
      { name: "Webots", note: "ROS 2-supported sim for quick multi-robot setups", note_ar: "محاكٍ مدعوم بـROS 2 لإعدادات سريعة متعددة الروبوتات", tag: "multi-robot" },
      { name: "Rviz 2", note: "The robot's-eye view — TF trees, point clouds, costmaps, planned paths", note_ar: "منظور الروبوت — أشجار TF، سُحُب النقاط، خرائط الكلفة، المسارات المخطّطة", tag: "viz" },
      { name: "FLIGHTGEN", note: "My automated ROS 2 UAV dataset generator", note_ar: "مولّد بيانات الطائرات الآلي بـROS 2", tag: "mine" },
      { name: "ROSNavBench", note: "My automated Nav2 trajectory-planner benchmark in Gazebo", note_ar: "أداتي لقياس مخطّطات مسار Nav2 في Gazebo", tag: "mine" },
    ],
  },
};

/* ── UI strings ── */
export const I18N = {
  en: {
    nav_about: "About", nav_research: "Research", nav_projects: "Projects", nav_gallery: "Gallery", nav_experience: "Experience",
    nav_cta: "Get in touch", lang_btn: "عربي",
    hero_kicker: "Robotics & Autonomous Intelligent Systems",
    hero_l1: "I build robots that", hero_l2: "fly, drive, and see.",
    hero_sub: "Senior Research Assistant at PSU's Robotics & IoT Lab — designing UAVs, ground robots, and the perception that keeps them located when GPS goes dark. Next stop: a PhD at KFUPM.",
    hero_cta1: "Explore the work →", hero_cta2: "Read the research",
    eb_about: "About", t_about: "From the CAD seed to the first flight.",
    about_p1: "Six years turning mechanical design, UAV autonomy, and reinforcement learning into machines that work in the real world — drones, ground robots, and the perception kits that keep them located when GPS goes dark.",
    about_origin: "It started as a childhood dream of being an inventor — not an engineer. The machines just made it real.",
    about_meta: "M.Sc. Robotics (KFUPM) · Senior Research Assistant at Prince Sultan University · heading to a PhD at KFUPM. Based in Riyadh, moving to Khobar.",
    eb_research: "Research", t_research: "A path through the publications.",
    lead_research: "Peer-reviewed work in UAV localization, trajectory prediction, ROS 2, and Arabic NLP — at ACM Computing Surveys, IEEE, Springer, and ACL.",
    eb_projects: "Projects", t_projects: "Eight machines, built to leave the bench.",
    lead_projects: "Drag to orbit the gallery — tap any project to open it. VTOLs, warehouse and hotel robots, agricultural drones, and the sensor kits behind them.",
    hint_sphere: "drag ⟲ to explore · tap to open",
    eb_gallery: "Gallery", t_gallery: "Hardware, in the metal.",
    gal_robots: "Robots & UAVs", gal_prints: "3D printing & fabrication",
    eb_patents: "Patents", t_patents: "Two granted industrial designs.",
    eb_track: "Track record", t_track: "Experience & education.", h_exp: "Experience", h_edu: "Education",
    eb_toolkit: "Toolkit", t_toolkit: "What I work with.",
    eb_oss: "Open source", t_oss: "Code on GitHub.", lead_oss: "ROS 2 stacks for UAV autonomy, drone-to-drone tracking, and simulation tooling.",
    eb_beyond: "Beyond work", t_beyond: "Discipline, off the clock.",
    lead_beyond: "When I'm not building robots, I train calisthenics — the same loop as engineering: small consistent reps, honest feedback, compounding gains. Faith, family, and fabrication keep the rest in balance.",
    eb_contact: "Contact", t_contact: "Let's build something that flies.",
    lb_close: "Close", lb_prev: "Previous", lb_next: "Next",
    tab_home: "Home", tab_beyond: "Beyond career",
    eb_stack: "How an autonomous robot thinks", t_stack: "My mental model of an autonomous robot.",
    lead_stack: "Not a stack — a loop. Perception flows up the left, decisions flow down the right, and the two meet at a shared world model, all watched by a safety supervisor and clocked at three timescales. Highlighted blocks are where my published and patented work lives.",
    stack_mine: "My work", stack_legend_mine: "Blocks I built / published", stack_legend_other: "Context blocks",
    arch_perc: "Perception ↑", arch_cog: "Decision & control ↓", arch_work_title: "Where my work lives",
    arch_aria: "Closed-loop autonomous-robot architecture: a perception pipeline ascending on the left, a decision-and-control column descending on the right, a shared world model at the centre, a supervisory layer, and a hardware layer — across three timing bands.",
    pubdb_title: "Browse every publication", pubdb_lead: "Search, filter by research area, and sort. Click a row for the abstract.",
    pubdb_search: "Search title, venue, tag…", pubdb_allyears: "All years", pubdb_allstatus: "All status",
    pubdb_count: "results", col_paper: "Paper", col_year: "Year", col_area: "Area", col_status: "Status", col_doi: "DOI",
    col_type: "Type", col_rank: "Rank", col_links: "Links", col_contrib: "Contribution", col_project: "Project page", pubdb_alltype: "All types", pub_copy: "Copy BibTeX", pub_copied: "Copied ✓", pub_project: "Project ↗", pub_page: "Visit ↗",
    role_first: "1st author", role_equal: "Equal contributor", role_co: "Co-author",
    tab_articles: "Writing", art_eb: "Writing", art_title: "Notes & articles.", art_lead: "Long-form writing on robotics, research, and building things — like a personal Medium.",
    art_empty: "No articles yet — coming soon.", art_min: "min read", art_back: "← All articles",
    st_published: "Published", st_accepted: "Accepted", st_review: "Under review", st_progress: "In progress",
    beyond_kicker: "Off the clock", beyond_title: "Beyond the lab.", beyond_lead: "The same discipline that builds robots — pointed at a mountain and a pull-up bar.",
    cal_eb: "Training", cal_title: "Calisthenics.", cal_lead: "Bodyweight strength — the engineer's loop: small consistent reps, honest feedback, gains that compound. A few of the moves I train:",
    research_more: "Browse the full publications database ↓",
    tab_gallery: "Gallery",
    hub_kicker: "Interests & craft", hub_title: "Six ways I build.", hub_sub: "Click the emblem to open it.",
    hub_back: "↩ All six", gal_flow_hint: "keep scrolling — the hardware drifts by",
    gp_drag: "drag ⟲ to spin · it also turns on its own", gp_pick: "Platforms",
    math_zeta: "damping ζ", math_wn: "frequency ωₙ",
    math_note: "A live second-order system — the mathematics under every mount, arm and airframe I tune.",
    sim_note: "Truth vs estimate: closing a GPS-denied flight loop in simulation first.",
    design_hint: "Each machine rotates by — click one for its design story.",
    cad_hint: "Renders from the CAD bench — click to zoom.",
    print_hint: "Procedural part meshes over a turntable — the real prints below.",
    /* ── v8 restructure ── */
    tab_research: "Research", tab_projects: "Projects",
    eb_journey: "The path so far", t_journey: "Education & career, from 2018.",
    lead_journey: "From the master's bench to a research lab — and next, a PhD. Follow the line.",
    j_edu: "Education", j_work: "Industry", j_milestone: "Milestone", j_next: "Incoming",
    eb_focus: "What I research", t_focus: "Four questions, one autonomous robot.",
    lead_focus: "My work lives where perception, learning, control, and systems overlap — around aerial, ground, and legged platforms.",
    focus_cta: "Open the research map →",
    rm_kicker: "Research interests", rm_title: "Where my research lives.",
    rm_lead: "Four overlapping fields around one shared goal — robots that sense, decide, and act on their own. Hover a field for the work behind it.",
    rm_hint: "Hover or tap a field", rm_platforms: "Platforms I build on",
    researchpg_lead: "The map, the mental model, and every publication — in one place.",
    projpg_kicker: "Projects", projpg_title: "The machines.",
    proj_intro: "Built to leave the bench. Filter by kind, then open any one for the full story.",
    proj_all: "All", proj_aerial: "Aerial", proj_ground: "Ground", proj_sensor: "Sensors & kits", proj_view: "View project",
    /* ── v9 ── */
    tab_teaching: "Teaching",
    teach_kicker: "Teaching", teach_title: "Courses & workshops.",
    teach_lead: "What I teach when I'm not building — ROS 2, autonomy, and the engineering design process, hands-on.",
    teach_courses: "University courses", teach_workshops: "Workshops & bootcamps",
    eb_orgs: "Organizations", t_orgs: "Where I build.", orgs_lead: "The labs and programs my research ships under.",
    org_follow: "View organization ↗", org_site: "Project site ↗",
    gp_photo: "Photo", gp_3d: "3D model",
    gp_trophy_hint: "Real STLs I designed and printed — use ‹ › to step through the collection.",
    gp_theory: "The theory behind it", sim_stack: "My ROS 2 sim + viz stack", gp_prints_h: "And in the real world",
  },
  ar: {
    nav_about: "نبذة", nav_research: "الأبحاث", nav_projects: "المشاريع", nav_gallery: "المعرض", nav_experience: "الخبرة",
    nav_cta: "تواصل معي", lang_btn: "EN",
    hero_kicker: "الروبوتات والأنظمة الذكية المستقلة",
    hero_l1: "أبني روبوتاتٍ", hero_l2: "تطير، وتسير، وتُبصر.",
    hero_sub: "باحث أول في معمل الروبوتات وإنترنت الأشياء بجامعة الأمير سلطان — أُصمّم طائرات مسيّرة وروبوتات أرضية والإدراك الذي يُبقيها متموضِعة حين ينقطع GPS. والوجهة القادمة: الدكتوراه في جامعة الملك فهد للبترول والمعادن.",
    hero_cta1: "استكشف الأعمال ←", hero_cta2: "اقرأ الأبحاث",
    eb_about: "نبذة", t_about: "من بذرة التصميم إلى أول إقلاع.",
    about_p1: "ستّ سنوات في تحويل التصميم الميكانيكي واستقلالية الطائرات والتعلّم المعزّز إلى آلاتٍ تعمل في الواقع — طائرات مسيّرة وروبوتات أرضية وحساسات تُبقيها متموضِعة حين ينقطع نظام تحديد المواقع.",
    about_origin: "بدأ الأمر حلمًا في الطفولة بأن أكون مُخترعًا — لا مهندسًا. والآلات هي ما جعلت الحلم حقيقة.",
    about_meta: "ماجستير الروبوتات (KFUPM) · باحث أول بجامعة الأمير سلطان · متوجّه إلى الدكتوراه في KFUPM. مقيم في الرياض ومنتقل إلى الخبر.",
    eb_research: "الأبحاث", t_research: "مسارٌ عبر المنشورات.",
    lead_research: "أعمال محكّمة في تموضع الطائرات وتوقّع المسارات وROS 2 ومعالجة اللغة العربية — في ACM Computing Surveys وIEEE وSpringer وACL.",
    eb_projects: "المشاريع", t_projects: "ثماني آلاتٍ بُنيت لتغادر الطاولة.",
    lead_projects: "اسحب لتدوير المعرض — واضغط على أي مشروع لفتحه. طائرات VTOL، وروبوتات مستودعات وفنادق، ودرون زراعي، والحساسات التي تقف خلفها.",
    hint_sphere: "اسحب ⟲ للاستكشاف · اضغط للفتح",
    eb_gallery: "المعرض", t_gallery: "العتاد، على الطبيعة.",
    gal_robots: "الروبوتات والطائرات", gal_prints: "الطباعة ثلاثية الأبعاد والتصنيع",
    eb_patents: "البراءات", t_patents: "تصميمان صناعيّان ممنوحان.",
    eb_track: "السجلّ", t_track: "الخبرة والتعليم.", h_exp: "الخبرة", h_edu: "التعليم",
    eb_toolkit: "الأدوات", t_toolkit: "ما أعمل به.",
    eb_oss: "مفتوح المصدر", t_oss: "شيفرات على GitHub.", lead_oss: "حزم ROS 2 لاستقلالية الطائرات، واعتراض الدرون بالدرون، وأدوات المحاكاة.",
    eb_beyond: "خارج العمل", t_beyond: "انضباطٌ بعيدًا عن المكتب.",
    lead_beyond: "حين لا أبني الروبوتات، أتمرّن على الكاليسثينكس — وهي الحلقة ذاتها في الهندسة: تكراراتٌ صغيرة ثابتة، وتغذية راجعة صادقة، ومكاسب تتراكم. الإيمان والعائلة والتصنيع تُبقي البقية متوازنة.",
    eb_contact: "تواصل", t_contact: "لنبنِ شيئًا يطير.",
    lb_close: "إغلاق", lb_prev: "السابق", lb_next: "التالي",
    tab_home: "الرئيسية", tab_beyond: "خارج العمل",
    eb_stack: "كيف يُفكّر روبوتٌ مستقل", t_stack: "نموذجي الذهني لروبوتٍ مستقل.",
    lead_stack: "ليست طبقات، بل حلقة: يصعد الإدراك على اليسار، وتنزل القرارات على اليمين، ويلتقيان عند نموذج عالمٍ مشترك، يراقبهما مشرفُ سلامة، ويُضبط الزمن على ثلاثة مقاييس. الكتل المميّزة هي حيث يقع عملي المنشور والمُبرَّأ.",
    stack_mine: "عملي", stack_legend_mine: "كتلٌ بنيتُها / نشرتُ فيها", stack_legend_other: "كتل سياقية",
    arch_perc: "الإدراك ↑", arch_cog: "القرار والتحكّم ↓", arch_work_title: "أين يقع عملي",
    arch_aria: "معمارية روبوت مستقل ذات حلقة مغلقة: مسار إدراك يصعد على اليسار، وعمود قرار وتحكّم ينزل على اليمين، ونموذج عالم مشترك في الوسط، وطبقة إشراف، وطبقة عتاد — عبر ثلاثة نطاقات زمنية.",
    pubdb_title: "تصفّح كل المنشورات", pubdb_lead: "ابحث، صفِّ حسب مجال البحث، ورتِّب. اضغط الصف لقراءة الملخّص.",
    pubdb_search: "ابحث في العنوان أو المحفل أو الوسم…", pubdb_allyears: "كل السنوات", pubdb_allstatus: "كل الحالات",
    pubdb_count: "نتيجة", col_paper: "البحث", col_year: "السنة", col_area: "المجال", col_status: "الحالة", col_doi: "DOI",
    col_type: "النوع", col_rank: "التصنيف", col_links: "روابط", col_contrib: "المساهمة", col_project: "صفحة المشروع", pubdb_alltype: "كل الأنواع", pub_copy: "انسخ BibTeX", pub_copied: "تم النسخ ✓", pub_project: "المشروع ↗", pub_page: "زيارة ↗",
    role_first: "مؤلف أول", role_equal: "مساهم مكافئ", role_co: "مؤلف مشارك",
    tab_articles: "مقالات", art_eb: "كتابات", art_title: "ملاحظات ومقالات.", art_lead: "كتابات مطوّلة عن الروبوتات والبحث وبناء الأشياء — كأنها مِديوم شخصية.",
    art_empty: "لا مقالات بعد — قريبًا.", art_min: "دقيقة قراءة", art_back: "← كل المقالات",
    st_published: "منشور", st_accepted: "مقبول", st_review: "قيد المراجعة", st_progress: "قيد العمل",
    beyond_kicker: "خارج الدوام", beyond_title: "خارج المختبر.", beyond_lead: "الانضباط نفسه الذي يبني الروبوتات — موجّهًا نحو جبلٍ وعقلة.",
    cal_eb: "تدريب", cal_title: "الكاليسثينكس.", cal_lead: "قوّة وزن الجسم — حلقة المهندس: تكراراتٌ صغيرة ثابتة، تغذية راجعة صادقة، ومكاسب تتراكم. بعض الحركات التي أتمرّن عليها:",
    research_more: "تصفّح قاعدة المنشورات كاملة ↓",
    tab_gallery: "المعرض",
    hub_kicker: "اهتمامات وحِرفة", hub_title: "ستّ طرائق أبني بها.", hub_sub: "اضغط على الشعار لفتحه.",
    hub_back: "↩ الستّ كلّها", gal_flow_hint: "تابع التمرير — العتاد ينساب أمامك",
    gp_drag: "اسحب ⟲ للتدوير · وهو يدور من تلقاء نفسه", gp_pick: "المنصّات",
    math_zeta: "التخميد ζ", math_wn: "التردد الطبيعي ωₙ",
    math_note: "نظام حيّ من الدرجة الثانية — الرياضيات الكامنة خلف كل حاملٍ وذراعٍ وهيكلٍ أضبطه.",
    sim_note: "المسار الحقيقي مقابل المُقدَّر: هكذا تُغلَق حلقة الطيران دون GPS في المحاكاة أولًا.",
    design_hint: "كل آلة تدور أمامك — اضغط عليها لقراءة قصة تصميمها.",
    cad_hint: "تصييرات من مشغل التصميم — اضغط للتكبير.",
    print_hint: "مجسّمات قطع فوق طاولة دوّارة — والمطبوعات الحقيقية أسفلها.",
    /* ── v8 restructure ── */
    tab_research: "الأبحاث", tab_projects: "المشاريع",
    eb_journey: "المسار حتى الآن", t_journey: "التعليم والمسيرة، منذ ٢٠١٨.",
    lead_journey: "من طاولة الماجستير إلى معمل بحثي — والقادم دكتوراه. تتبّع الخطّ.",
    j_edu: "تعليم", j_work: "صناعة", j_milestone: "محطة", j_next: "قادم",
    eb_focus: "ما أبحث فيه", t_focus: "أربعة أسئلة، وروبوتٌ مستقلّ واحد.",
    lead_focus: "يقع عملي حيث يتقاطع الإدراك والتعلّم والتحكّم والأنظمة — حول منصّات جوية وأرضية ورباعية.",
    focus_cta: "افتح خارطة الأبحاث ←",
    rm_kicker: "اهتمامات بحثية", rm_title: "أين تقع أبحاثي.",
    rm_lead: "أربعة حقول متداخلة حول هدف واحد — روبوتات تُدرك وتقرّر وتتصرّف ذاتيًا. مرّر المؤشّر على حقلٍ لترى العمل خلفه.",
    rm_hint: "مرّر أو اضغط على حقل", rm_platforms: "المنصّات التي أبني عليها",
    researchpg_lead: "الخارطة، والنموذج الذهني، وكل منشور — في مكان واحد.",
    projpg_kicker: "المشاريع", projpg_title: "الآلات.",
    proj_intro: "بُنيت لتغادر الطاولة. صفِّ حسب النوع، ثم افتح أيّها لقراءة القصة كاملة.",
    proj_all: "الكل", proj_aerial: "جوية", proj_ground: "أرضية", proj_sensor: "حساسات وعُدد", proj_view: "عرض المشروع",
    /* ── v9 ── */
    tab_teaching: "التدريس",
    teach_kicker: "التدريس", teach_title: "مقرّرات وورش.",
    teach_lead: "ما أُدرّسه حين لا أبني — ROS 2 والاستقلالية ومنهجية التصميم الهندسي، عمليًّا.",
    teach_courses: "مقرّرات جامعية", teach_workshops: "ورش ومعسكرات",
    eb_orgs: "المنظّمات", t_orgs: "أين أبني.", orgs_lead: "المعامل والبرامج التي تُنشر تحتها أبحاثي.",
    org_follow: "زيارة المنظّمة ↗", org_site: "موقع المشروع ↗",
    gp_photo: "صورة", gp_3d: "مجسّم ثلاثي",
    gp_trophy_hint: "مجسّمات STL حقيقية صمّمتها وطبعتها — استخدم ‹ › للتنقّل في المجموعة.",
    gp_theory: "النظرية خلفه", sim_stack: "منظومة المحاكاة والعرض بـROS 2", gp_prints_h: "وفي الواقع",
  },
};
